// Generated by packages/core/script/deferred-builtins.ts. Do not edit.
import { ToolDefinition } from "@novaclaw/llm"
import { makeLocationNode } from "../../effect/app-node"
import { LazyBuiltin } from "../lazy-builtin"
import { Config } from "../../config"
import { Image } from "../../image"
import { Location } from "../../location"
import { Offline } from "../../offline"
import { AppProcess } from "../../process"
import { PermissionV2 } from "../../permission"
import { SessionComponentRegistry } from "../../session/component-registry"
import { SessionStore } from "../../session/store"
import { ToolRegistry } from ".././registry"

export const node = makeLocationNode({
name: "tool/computer",
layer: LazyBuiltin.layer({
definition: new ToolDefinition({
  "name": "computer",
  "description": "Observe and control a graphical desktop: bind, screenshot, move, click, type, key, scroll, copy text.\n\nPreferred keyboard call: {\"action\":\"key\",\"keys\":\"ctrl+o\"}. Nova also normalizes the common Computer Use forms {\"action\":\"keypress\",\"keys\":[\"CTRL\",\"O\"]} and {\"action\":\"keyDown\",\"buttons\":[\"ctrl\",\"o\"]}.\n\nFor tasks with no API and no text interface — a native app, a game, a site that will not work headlessly. Prefer a dedicated tool when one exists; this is the slow fallback.\n\n`bind` is the ONLY real-desktop entry. On Windows, give the approved executable basename in `app` (for example `dosbox-x.exe`); Nova finds exactly one visible top-level window and binds its HWND/PID/executable identity. On X11, approval gives the human 60 seconds to click one window on `display`. Later calls can see and address only that exact application window; ordinary actions use the durable grant.\n\n`screenshot` returns the captured image in its own result — look at it directly; do not call `read` on the path.\n\nOn Windows, x/y use the vision model's 0–1000 logical grid from top-left to bottom-right, independent of window size. X11 uses screenshot pixels. Screenshot first and read the target off it; never reuse a position from before an action, because what you clicked may have moved it.\n\nOn an approved Windows application, `copy_text` atomically selects all, copies, and returns text from that exact foreground window. It never reads old clipboard contents. Use it for a long browser article after a screenshot proves the correct page is open.\n\n⚠️ Verify by looking: a click that lands on nothing still reports success, so the only evidence it worked is the screen changing.",
  "inputSchema": {
    "$ref": "#/$defs/ComputerTool.Input",
    "$defs": {
      "ComputerTool.Input": {
        "type": "object",
        "properties": {
          "action": {
            "type": "string",
            "enum": [
              "bind",
              "screenshot",
              "move",
              "mouse_move",
              "click",
              "click_element",
              "left_click",
              "right_click",
              "double_click",
              "doubleClick",
              "type",
              "type_submit",
              "key",
              "keypress",
              "keyDown",
              "press_key",
              "press",
              "key_sequence",
              "scroll",
              "scroll_down",
              "copy_text",
              "cursor"
            ],
            "description": "What to do."
          },
          "display": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "description": "X11 display used only by `bind`, e.g. \":0\". Approval plus the user clicking a window creates the scoped grant."
          },
          "app": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "description": "Windows executable basename used only by `bind`, e.g. \"dosbox-x.exe\" or \"chrome.exe\"."
          },
          "x": {
            "anyOf": [
              {
                "anyOf": [
                  {
                    "type": "number"
                  },
                  {
                    "type": "string"
                  }
                ]
              },
              {
                "type": "null"
              }
            ],
            "description": "Target X (Windows: 0–1000 grid; X11: pixels). Numeric strings are tolerated."
          },
          "y": {
            "anyOf": [
              {
                "anyOf": [
                  {
                    "type": "number"
                  },
                  {
                    "type": "string"
                  }
                ]
              },
              {
                "type": "null"
              }
            ],
            "description": "Target Y (Windows: 0–1000 grid; X11: pixels). Numeric strings are tolerated."
          },
          "button": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "description": "Mouse button for `click` (\"left\", \"middle\", or \"right\"). Defaults to left."
          },
          "double": {
            "anyOf": [
              {
                "type": "boolean"
              },
              {
                "type": "null"
              }
            ],
            "description": "Compatibility flag: `click` with true is a double-click; prefer action `double_click`."
          },
          "text": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "description": "Literal text for `type`."
          },
          "submit": {
            "anyOf": [
              {
                "type": "boolean"
              },
              {
                "type": "null"
              }
            ],
            "description": "Compatibility flag: type text, then press Enter; prefer action type_submit."
          },
          "keys": {
            "anyOf": [
              {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  }
                ]
              },
              {
                "type": "null"
              }
            ],
            "description": "Key combination for `key`: preferably \"ctrl+s\"; [\"CTRL\",\"S\"] is also accepted."
          },
          "buttons": {
            "anyOf": [
              {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              {
                "type": "null"
              }
            ],
            "description": "Compatibility alias for a keyboard key array; prefer `keys`."
          },
          "key": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "description": "Compatibility alias for one keyboard key; prefer `keys`."
          },
          "direction": {
            "anyOf": [
              {
                "anyOf": [
                  {
                    "type": "string",
                    "enum": [
                      "up",
                      "down",
                      "left",
                      "right"
                    ]
                  },
                  {
                    "type": "number"
                  },
                  {
                    "type": "string"
                  }
                ]
              },
              {
                "type": "null"
              }
            ],
            "description": "Scroll direction."
          },
          "amount": {
            "anyOf": [
              {
                "anyOf": [
                  {
                    "type": "number"
                  },
                  {
                    "type": "string"
                  }
                ]
              },
              {
                "type": "null"
              }
            ],
            "description": "Scroll clicks (1-25); larger pixel-style values are normalized safely."
          },
          "height": {
            "anyOf": [
              {
                "anyOf": [
                  {
                    "type": "number"
                  },
                  {
                    "type": "string"
                  }
                ]
              },
              {
                "type": "null"
              }
            ],
            "description": "Compatibility alias for a pixel-style scroll distance; prefer amount."
          },
          "delta_y": {
            "anyOf": [
              {
                "anyOf": [
                  {
                    "type": "number"
                  },
                  {
                    "type": "string"
                  }
                ]
              },
              {
                "type": "null"
              }
            ],
            "description": "Compatibility vertical wheel delta; Holo's measured negative value means down."
          },
          "speed": {
            "anyOf": [
              {
                "anyOf": [
                  {
                    "type": "number"
                  },
                  {
                    "type": "string"
                  }
                ]
              },
              {
                "type": "null"
              }
            ],
            "description": "Compatibility alias for vertical wheel delta; prefer direction plus amount."
          },
          "region": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "description": "Optional crop for `screenshot`, as \"x,y,width,height\" in screen pixels (e.g. \"100,120,240,180\"). Use it when part of the screen animates on its own — an attract loop, a video, a clock — so a whole-screen capture cannot tell you whether YOUR action changed anything."
          }
        },
        "required": [
          "action"
        ],
        "additionalProperties": false
      }
    }
  },
  "outputSchema": {
    "type": "object",
    "properties": {
      "action": {
        "type": "string"
      },
      "ok": {
        "type": "boolean"
      },
      "detail": {
        "type": "string"
      },
      "screenshotPath": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      }
    },
    "required": [
      "action",
      "ok",
      "detail"
    ],
    "additionalProperties": false
  }
}),
sideEffect: "non-idempotent",
load: () => import("../computer"),

}),
deps: [
    ToolRegistry.node,
    PermissionV2.node,
    AppProcess.node,
    Location.node,
    Config.node,
    Image.node,
    SessionStore.node,
    SessionComponentRegistry.node,
    Offline.node,
  ],
})
