// Generated by packages/core/script/deferred-builtins.ts. Do not edit.
import { ToolDefinition } from "@novaclaw/llm"
import { makeLocationNode } from "../../effect/app-node"
import { LazyBuiltin } from "../lazy-builtin"
import { AgentConfigStore } from "../../agent-config-store"
import { CatalogStore } from "../../catalog-store"
import { CommandConfigStore } from "../../command-config-store"
import { Database } from "../../database/database"
import { CapabilityRegistry } from "../../effect/capability-registry"
import { PermissionV2 } from "../../permission"
import { ReferenceConfigStore } from "../../reference-config-store"
import { SettingsConfigStore } from "../../settings-config-store"
import { SkillConfigStore } from "../../skill-config-store"
import { ToolRegistry } from ".././registry"

export const node = makeLocationNode({
name: "tool/configure",
layer: LazyBuiltin.layer({
definition: new ToolDefinition({
  "name": "configure",
  "description": "Repair or change THIS instance's own configuration — provider endpoints, models, presets, and every instance setting — without editing files or restarting. Ops: {\"op\":\"schema\"} — every configuration key in one line: what it is and what changing it costs · {\"op\":\"schema\",\"keys\":[\"providers\"],\"depth\":2} — one key's FIELDS: what each means, its legal values, and the exact shape a write must take · {\"op\":\"read\"} — what this instance currently HOLDS, every key · {\"op\":\"read\",\"keys\":[\"providers\"]} — one key's current value in full · {\"op\":\"set\",\"config\":{\"models\":{\"qwen\":{\"url\":\"http://192.168.1.5:8000/v1\"}}}} — write · {\"op\":\"remove\",\"paths\":[[\"mcp\",\"servers\",\"filesystem\"]]} — DELETE. {\"op\":\"retry\",\"capability\":\"memory\"} — retry one cached capability failure after repairing it. ASK FOR THE SCHEMA BEFORE YOU WRITE A KEY YOU HAVE NOT WRITTEN BEFORE: `read` shows a VALUE and shows nothing at all for a key that was never set, while `schema` always names the fields, says which are required, and says whether a fragment is enough — some keys refuse a partial patch outright, so a guessed fragment is rejected whole. A field name this instance does not have is refused by name rather than quietly dropped. Values MERGE into what is stored (objects merge, arrays replace wholesale), so `set` can never remove anything — a null SETS null. Use `remove`, whose paths are ARRAYS OF SEGMENTS, never dotted strings. Most writes ask the user first and say so before anything is stored; a write that is refused changes nothing at all. Credentials are writable and never read back.",
  "inputSchema": {
    "anyOf": [
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "schema"
            ]
          },
          "keys": {
            "anyOf": [
              {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              {
                "type": "null"
              }
            ],
            "description": "Configuration keys to describe in full, e.g. [\"providers\",\"mcp\"]. Omit to survey every key, one line each."
          },
          "depth": {
            "anyOf": [
              {
                "anyOf": [
                  {
                    "type": "number"
                  },
                  {
                    "type": "string",
                    "enum": [
                      "NaN"
                    ]
                  },
                  {
                    "type": "string",
                    "enum": [
                      "Infinity"
                    ]
                  },
                  {
                    "type": "string",
                    "enum": [
                      "-Infinity"
                    ]
                  }
                ]
              },
              {
                "type": "null"
              }
            ],
            "description": "How many levels of nested fields to expand under each requested key. Default 1, maximum 4; a larger value is clamped, not refused. Only meaningful together with `keys`."
          }
        },
        "required": [
          "op"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "read"
            ]
          },
          "keys": {
            "anyOf": [
              {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              {
                "type": "null"
              }
            ],
            "description": "Configuration keys to show in full, e.g. [\"providers\",\"model\"]. Omit to survey every key (values abbreviated)."
          }
        },
        "required": [
          "op"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "set"
            ]
          },
          "config": {
            "type": "object",
            "description": "A configuration patch: top-level configuration keys mapped to their new values, exactly the shape `read` shows. Example: {\"models\":{\"qwen\":{\"url\":\"http://192.168.1.5:8000/v1\"}}}. Objects merge into what is stored; arrays replace wholesale. A key or a field this instance does not have is refused and named, so read the key first if you are unsure of its shape."
          }
        },
        "required": [
          "op",
          "config"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "remove"
            ]
          },
          "paths": {
            "type": "array",
            "items": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "description": "Configuration locations to delete, each an ARRAY OF SEGMENTS (never a dotted string — config ids contain dots and slashes). Examples: [\"mcp\",\"servers\",\"filesystem\"] removes one MCP server; [\"providers\",\"spark-holo\",\"models\",\"holo3.1\"] removes one stale model and keeps its provider; [\"model\"] clears the default model. Applied all-or-nothing: if any path names nothing, NOTHING is removed and the reply says which one."
          }
        },
        "required": [
          "op",
          "paths"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "retry"
            ]
          },
          "capability": {
            "type": "string",
            "description": "The exact capability name from its unavailable notice, e.g. \"memory\" or \"local-model\". Retries one cached startup failure after its repair; it does not restart the instance."
          }
        },
        "required": [
          "op",
          "capability"
        ],
        "additionalProperties": false
      }
    ]
  },
  "outputSchema": {
    "type": "object",
    "properties": {
      "op": {
        "type": "string",
        "enum": [
          "schema",
          "read",
          "set",
          "remove",
          "retry"
        ]
      },
      "message": {
        "type": "string"
      }
    },
    "required": [
      "op",
      "message"
    ],
    "additionalProperties": false
  }
}),
sideEffect: "external-unknown",
load: () => import("../configure"),

}),
deps: [
    ToolRegistry.node,
    PermissionV2.node,
    Database.node,
    SettingsConfigStore.node,
    CatalogStore.node,
    AgentConfigStore.node,
    CommandConfigStore.node,
    ReferenceConfigStore.node,
    SkillConfigStore.node,
    CapabilityRegistry.node,
  ],
})
