// Generated by packages/core/script/deferred-builtins.ts. Do not edit.
import { ToolDefinition } from "@novaclaw/llm"
import { makeLocationNode } from "../../effect/app-node"
import { LazyBuiltin } from "../lazy-builtin"
import { Database } from "../../database/database"
import { PermissionV2 } from "../../permission"
import { ToolRegistry } from ".././registry"

export const node = makeLocationNode({
name: "tool/db-registry",
layer: LazyBuiltin.layer({
definition: new ToolDefinition({
  "name": "registry",
  "description": "Browse and edit THIS instance's SQLite database directly — the same surface the Developer-mode\nRegistry app gives a person. Use it to inspect or repair state that lives only in the database and\nhas no other tool, after you have established from the log what is actually wrong.\nOps: {op:'tables'} — every table with its row count (start here);\n{op:'rows',table,limit?,offset?} — a page of rows, each with the `rowid` the write ops take;\n{op:'insert',table,values} · {op:'update',table,rowid,values} · {op:'delete',table,rowid}.\nConfiguration tables are read-only here — change settings with `configure`, which applies their\npermission rules. The permission kernel's own tables (`permission`, `session_auto_grant`) are\nread-only too: if you need an action you do not have, ask for it in your reply. The\nschema-migration journal is read-only to everyone.\nStored credentials come back redacted — passwords, API tokens, peer tokens and signing keys are\nreplaced with a placeholder, so a value you read here is never one you can use.\nBrowsing is free; each insert/update/delete spends the `registry_write` permission for the one\ntable it names, so read first and write once.",
  "inputSchema": {
    "anyOf": [
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "tables"
            ]
          }
        },
        "required": [
          "op"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "rows"
            ]
          },
          "table": {
            "type": "string",
            "description": "Table name, exactly as {op:'tables'} reports it"
          },
          "limit": {
            "anyOf": [
              {
                "type": "number"
              },
              {
                "type": "null"
              }
            ],
            "description": "Rows to return (default 50)"
          },
          "offset": {
            "anyOf": [
              {
                "type": "number"
              },
              {
                "type": "null"
              }
            ],
            "description": "Rows to skip, for paging"
          }
        },
        "required": [
          "op",
          "table"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "insert"
            ]
          },
          "table": {
            "type": "string"
          },
          "values": {
            "type": "object",
            "description": "Column → value. Unknown columns are dropped, never interpolated."
          }
        },
        "required": [
          "op",
          "table",
          "values"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "update"
            ]
          },
          "table": {
            "type": "string"
          },
          "rowid": {
            "type": "number",
            "allOf": [
              {
                "description": "The `rowid` {op:'rows'} returned for this row"
              }
            ]
          },
          "values": {
            "type": "object"
          }
        },
        "required": [
          "op",
          "table",
          "rowid",
          "values"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "delete"
            ]
          },
          "table": {
            "type": "string"
          },
          "rowid": {
            "type": "number"
          }
        },
        "required": [
          "op",
          "table",
          "rowid"
        ],
        "additionalProperties": false
      }
    ]
  },
  "outputSchema": {
    "type": "object",
    "properties": {
      "ok": {
        "type": "boolean"
      },
      "message": {
        "type": "string"
      }
    },
    "required": [
      "ok",
      "message"
    ],
    "additionalProperties": false
  }
}),
sideEffect: "external-unknown",
load: () => import("../db-registry"),

}),
deps: [ToolRegistry.node, Database.node, PermissionV2.node],
})
