// Generated by packages/core/script/deferred-builtins.ts. Do not edit.
import { ToolDefinition } from "@novaclaw/llm"
import { makeLocationNode } from "../../effect/app-node"
import { LazyBuiltin } from "../lazy-builtin"
import { PermissionV2 } from "../../permission"
import { SessionComponentRegistry } from "../../session/component-registry"
import { ToolRegistry } from ".././registry"

export const node = makeLocationNode({
name: "tool/durable-set",
layer: LazyBuiltin.layer({
definition: new ToolDefinition({
  "name": "durable_set",
  "description": "Keep a short named item in this session's durable area: a place for the handful of facts that must survive a context rewrite (a path that matters, a decision already made, what the user is waiting for). The area holds at most 10 items and is rebuilt into your system prompt after each compaction, so a write here reaches the prompt from the next rewrite onwards — read it back sooner with the `session` tool (`kind: \"durable\"`). Reusing a name replaces that item. Nothing is evicted for you: clear what you no longer need with `durable_clear`.",
  "inputSchema": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "description": "The item's short name — at most 30 characters, one line. Reusing a name replaces that item."
      },
      "value": {
        "type": "string",
        "description": "The item's value — at most 512 characters, one line. Too long? Write the text to a file in your scratch folder and put that path here."
      }
    },
    "required": [
      "name",
      "value"
    ],
    "additionalProperties": false
  },
  "outputSchema": {
    "type": "object",
    "properties": {
      "message": {
        "type": "string"
      }
    },
    "required": [
      "message"
    ],
    "additionalProperties": false
  }
}),
sideEffect: "external-unknown",
load: () => import("../durable-set"),

}),
deps: [ToolRegistry.node, PermissionV2.node, SessionComponentRegistry.node],
})
