// Generated by packages/core/script/deferred-builtins.ts. Do not edit.
import { ToolDefinition } from "@novaclaw/llm"
import { makeLocationNode } from "../../effect/app-node"
import { LazyBuiltin } from "../lazy-builtin"
import { PermissionV2 } from "../../permission"
import { SessionComponentRegistry } from "../../session/component-registry"
import { ToolRegistry } from ".././registry"

export const node = makeLocationNode({
name: "tool/durable-clear",
layer: LazyBuiltin.layer({
definition: new ToolDefinition({
  "name": "durable_clear",
  "description": "Remove one item from this session's durable area by name. Nothing is evicted automatically, so this is how room is made once the area is full. The item leaves the shadow immediately; the block in your system prompt drops it at the next compaction.",
  "inputSchema": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "description": "The name of the item to clear."
      }
    },
    "required": [
      "name"
    ],
    "additionalProperties": false
  },
  "outputSchema": {
    "type": "object",
    "properties": {
      "message": {
        "type": "string"
      }
    },
    "required": [
      "message"
    ],
    "additionalProperties": false
  }
}),
sideEffect: "external-unknown",
load: () => import("../durable-clear"),

}),
deps: [ToolRegistry.node, PermissionV2.node, SessionComponentRegistry.node],
})
