// Generated by packages/core/script/deferred-builtins.ts. Do not edit.
import { ToolDefinition } from "@novaclaw/llm"
import { makeLocationNode } from "../../effect/app-node"
import { LazyBuiltin } from "../lazy-builtin"
import { Memory } from "../../kb-graph/memory"
import { LocationMutation } from "../../location-mutation"
import { PermissionV2 } from "../../permission"
import { SessionEffectiveConfig } from "../../session/effective-config"
import { ToolRegistry } from ".././registry"

export const node = makeLocationNode({
name: "tool/kb",
layer: LazyBuiltin.layer({
definition: new ToolDefinition({
  "name": "kb",
  "description": "The agent's long-term memory — a knowledge GRAPH. Ops: search (find things you've remembered, by keyword) · remember (save a fact; returns its id — default durably across all chats; give `name` + `predicate` and a NEW answer retires the old one instead of piling up beside it) · history (what a memory replaced, and what it rested on) · relate (link two remembered ids with a relationship like works_at, so you can later trace multi-step connections neighbors/search alone can't) · forget (drop a memory by id) · neighbors (memories linked to one you found) · ingest (read a text DOCUMENT at a path into memory as searchable passages — the file never enters your context, so ingest a big manual then search it). Chain them: remember the entities, then relate what connects them. Example: {\"op\":\"remember\",\"text\":\"Ada Lovelace\",\"name\":\"Ada\"} → {\"op\":\"relate\",\"from\":\"mem_…\",\"to\":\"mem_…\",\"type\":\"wrote\"}.",
  "inputSchema": {
    "anyOf": [
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "search"
            ]
          },
          "query": {
            "type": "string",
            "description": "Free-text query; matches remembered facts by keyword"
          },
          "k": {
            "anyOf": [
              {
                "type": "number"
              },
              {
                "type": "null"
              }
            ],
            "description": "Max results (default 8)"
          },
          "scope": {
            "anyOf": [
              {
                "type": "string",
                "enum": [
                  "session",
                  "agent",
                  "global",
                  "all"
                ]
              },
              {
                "type": "null"
              }
            ],
            "description": "session = this chat only · agent = your own memory, across your chats · global = shared facts every agent knows · all (default)"
          }
        },
        "required": [
          "op",
          "query"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "remember"
            ]
          },
          "text": {
            "type": "string",
            "description": "The fact to remember, as one clear standalone sentence"
          },
          "name": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "description": "Short subject/label (e.g. the person or thing it's about)"
          },
          "predicate": {
            "anyOf": [
              {
                "type": "string",
                "enum": [
                  "about",
                  "birthday",
                  "dislikes",
                  "email",
                  "employer",
                  "knows",
                  "language",
                  "likes",
                  "location",
                  "name",
                  "owner",
                  "path",
                  "phone",
                  "preference",
                  "role",
                  "status",
                  "timezone",
                  "uses",
                  "version",
                  "works_on"
                ]
              },
              {
                "type": "null"
              }
            ],
            "description": "Which question about `name` this answers. Use it when the fact REPLACES an older answer: employer, role, location, email, phone, timezone, language, birthday, preference, status, version, path, owner and name each have ONE current answer, so saving a new one retires the old one (kept in history). about/likes/dislikes/knows/uses/works_on accumulate instead. Default: about."
          },
          "scope": {
            "anyOf": [
              {
                "type": "string",
                "enum": [
                  "session",
                  "agent",
                  "global"
                ]
              },
              {
                "type": "null"
              }
            ],
            "description": "agent (default) = your own durable memory · global = a fact about the user or household that every agent should know · session = only this chat"
          }
        },
        "required": [
          "op",
          "text"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "forget"
            ]
          },
          "id": {
            "type": "string",
            "description": "A memory id from search results (mem_…)"
          },
          "secret": {
            "anyOf": [
              {
                "type": "boolean"
              },
              {
                "type": "null"
              }
            ],
            "description": "true = hard-delete with no history (for secrets/credentials); default keeps it in history"
          }
        },
        "required": [
          "op",
          "id"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "neighbors"
            ]
          },
          "id": {
            "type": "string",
            "description": "A memory id (mem_…) whose directly-linked memories to list"
          },
          "k": {
            "anyOf": [
              {
                "type": "number"
              },
              {
                "type": "null"
              }
            ],
            "description": "Max results (default 10)"
          }
        },
        "required": [
          "op",
          "id"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "relate"
            ]
          },
          "from": {
            "type": "string",
            "description": "The subject memory id (mem_… from a remember/search result)"
          },
          "to": {
            "type": "string",
            "description": "The object memory id (mem_… from a remember/search result)"
          },
          "type": {
            "type": "string",
            "description": "The relationship as a short verb phrase, e.g. works_at, wrote, located_in, part_of, depends_on"
          }
        },
        "required": [
          "op",
          "from",
          "to",
          "type"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "ingest"
            ]
          },
          "path": {
            "type": "string",
            "description": "Path to a text document to read into memory as searchable passages. The document does NOT enter your context — ingest a big file, then `search` it."
          },
          "name": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "description": "Short label for the source (defaults to the file name)"
          },
          "scope": {
            "anyOf": [
              {
                "type": "string",
                "enum": [
                  "session",
                  "agent",
                  "global"
                ]
              },
              {
                "type": "null"
              }
            ],
            "description": "agent (default) = readable in your own chats · global = readable by every agent · session = only this chat"
          }
        },
        "required": [
          "op",
          "path"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "history"
            ]
          },
          "id": {
            "type": "string",
            "description": "A memory id (clm_… or mem_…) whose history to show — what it replaced, and why"
          }
        },
        "required": [
          "op",
          "id"
        ],
        "additionalProperties": false
      }
    ]
  },
  "outputSchema": {
    "type": "object",
    "properties": {
      "ok": {
        "type": "boolean"
      },
      "message": {
        "type": "string"
      }
    },
    "required": [
      "ok",
      "message"
    ],
    "additionalProperties": false
  }
}),
sideEffect: "external-unknown",
load: () => import("../kb"),

}),
deps: [ToolRegistry.node, Memory.node, LocationMutation.node, PermissionV2.node, SessionEffectiveConfig.node],
})
