// Generated by packages/core/script/deferred-builtins.ts. Do not edit.
import { ToolDefinition } from "@novaclaw/llm"
import { makeLocationNode } from "../../effect/app-node"
import { LazyBuiltin } from "../lazy-builtin"
import { ToolRegistry } from ".././registry"

export const node = makeLocationNode({
name: "tool/log",
layer: LazyBuiltin.layer({
definition: new ToolDefinition({
  "name": "log",
  "description": "Read THIS instance's own log — the record of what the OS actually did. Use it whenever something\nfailed, hung, or behaved unexpectedly and you need the real cause rather than a guess, and before\nreporting that something is broken.\nOps: {op:'keys',subsystem?,level?,match?} — the declared event vocabulary (start here);\n{op:'read',level?,key?,subsystem?,correlator?,match?,since?,limit?,plane?} — matching lines;\n{op:'count',by?,...same filters} — how often each event fired.\nLines are logfmt: event=<subsystem.object.action> names the event, and values are named columns.",
  "inputSchema": {
    "anyOf": [
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "read"
            ]
          },
          "level": {
            "anyOf": [
              {
                "type": "string",
                "enum": [
                  "debug",
                  "info",
                  "warn",
                  "error"
                ]
              },
              {
                "type": "null"
              }
            ],
            "description": "Minimum severity — a floor. 'warn' returns warnings and errors."
          },
          "key": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "description": "An event key or a dotted prefix of one, e.g. 'session.' or 'mcp.server.spawn.failed'"
          },
          "subsystem": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "description": "One subsystem name — the first segment of a key. See {op:'keys'}."
          },
          "correlator": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "description": "An exact id to follow across lines: a session id, a pty id, a workspace id."
          },
          "match": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "description": "Case-insensitive substring anywhere on the line. Use it to search error text."
          },
          "since": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "description": "Only lines newer than this age: '30m', '4h', '2d'."
          },
          "limit": {
            "anyOf": [
              {
                "type": "number"
              },
              {
                "type": "null"
              }
            ],
            "description": "Newest matching lines (default 40)"
          },
          "plane": {
            "anyOf": [
              {
                "type": "string",
                "enum": [
                  "local",
                  "maintenance"
                ]
              },
              {
                "type": "null"
              }
            ],
            "description": "'local' (default) returns the lines in full — this instance's own log, for repairing it. 'maintenance' withholds every column that may not leave this machine, for a report you send onward."
          }
        },
        "required": [
          "op"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "count"
            ]
          },
          "level": {
            "anyOf": [
              {
                "type": "string",
                "enum": [
                  "debug",
                  "info",
                  "warn",
                  "error"
                ]
              },
              {
                "type": "null"
              }
            ],
            "description": "Minimum severity — a floor. 'warn' returns warnings and errors."
          },
          "key": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "description": "An event key or a dotted prefix of one, e.g. 'session.' or 'mcp.server.spawn.failed'"
          },
          "subsystem": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "description": "One subsystem name — the first segment of a key. See {op:'keys'}."
          },
          "correlator": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "description": "An exact id to follow across lines: a session id, a pty id, a workspace id."
          },
          "match": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "description": "Case-insensitive substring anywhere on the line. Use it to search error text."
          },
          "since": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "description": "Only lines newer than this age: '30m', '4h', '2d'."
          },
          "by": {
            "anyOf": [
              {
                "type": "string",
                "enum": [
                  "event",
                  "level",
                  "subsystem"
                ]
              },
              {
                "type": "null"
              }
            ],
            "description": "Group by (default 'event')"
          }
        },
        "required": [
          "op"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "keys"
            ]
          },
          "subsystem": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "description": "Only this subsystem's events"
          },
          "level": {
            "anyOf": [
              {
                "type": "string",
                "enum": [
                  "debug",
                  "info",
                  "warn",
                  "error"
                ]
              },
              {
                "type": "null"
              }
            ],
            "description": "Only events declared at this level or above"
          },
          "match": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "description": "Substring over the key and its message"
          }
        },
        "required": [
          "op"
        ],
        "additionalProperties": false
      }
    ]
  },
  "outputSchema": {
    "type": "object",
    "properties": {
      "ok": {
        "type": "boolean"
      },
      "message": {
        "type": "string"
      }
    },
    "required": [
      "ok",
      "message"
    ],
    "additionalProperties": false
  }
}),
sideEffect: "external-unknown",
load: () => import("../log"),

}),
deps: [ToolRegistry.node],
})
