// Generated by packages/core/script/deferred-builtins.ts. Do not edit.
import { ToolDefinition } from "@novaclaw/llm"
import { makeLocationNode } from "../../effect/app-node"
import { LazyBuiltin } from "../lazy-builtin"
import { AgentConfigStore } from "../../agent-config-store"
import { AgentV2 } from "../../agent"
import { PermissionV2 } from "../../permission"
import { ToolRegistry } from ".././registry"
import { NudgeService } from "../../nudge-service"

export const node = makeLocationNode({
name: "tool/nudge",
layer: LazyBuiltin.layer({
definition: new ToolDefinition({
  "name": "nudge",
  "description": "List, view, add, edit, enable, disable, or delete personal Nudges for yourself or an officer below you in the reporting chain. A nudge may run a bounded bash command in $(...) at delivery. Before-tool nudges require nudge confirm before retrying the same call.",
  "inputSchema": {
    "anyOf": [
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "list"
            ]
          },
          "target": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "required": [
          "op"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "view"
            ]
          },
          "id": {
            "type": "string"
          },
          "target": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "required": [
          "op",
          "id"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "add",
              "edit"
            ]
          },
          "target": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "nudge": {
            "$ref": "#/$defs/ConfigV2.Nudge"
          }
        },
        "required": [
          "op",
          "nudge"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "delete",
              "disable",
              "enable"
            ]
          },
          "id": {
            "type": "string"
          },
          "target": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "required": [
          "op",
          "id"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "confirm"
            ]
          },
          "id": {
            "type": "string"
          },
          "callId": {
            "type": "string"
          }
        },
        "required": [
          "op",
          "id",
          "callId"
        ],
        "additionalProperties": false
      }
    ],
    "$defs": {
      "ConfigV2.Nudge": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "enabled": {
            "anyOf": [
              {
                "type": "boolean"
              },
              {
                "type": "null"
              }
            ]
          },
          "hook": {
            "anyOf": [
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "text-match"
                    ]
                  },
                  "pattern": {
                    "type": "string"
                  }
                },
                "required": [
                  "type",
                  "pattern"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "write-match"
                    ]
                  },
                  "pattern": {
                    "type": "string"
                  }
                },
                "required": [
                  "type",
                  "pattern"
                ],
                "additionalProperties": false,
                "description": "Fires when the content a writing tool is about to write matches the pattern. Never tested against a tool's OUTPUT, so text the agent merely read cannot fire it."
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "tool-call"
                    ]
                  },
                  "tool": {
                    "type": "string"
                  },
                  "phase": {
                    "anyOf": [
                      {
                        "type": "string",
                        "enum": [
                          "before",
                          "after"
                        ]
                      },
                      {
                        "type": "null"
                      }
                    ]
                  }
                },
                "required": [
                  "type",
                  "tool"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "shell-command"
                    ]
                  },
                  "pattern": {
                    "type": "string"
                  },
                  "phase": {
                    "anyOf": [
                      {
                        "type": "string",
                        "enum": [
                          "before",
                          "after"
                        ]
                      },
                      {
                        "type": "null"
                      }
                    ]
                  }
                },
                "required": [
                  "type",
                  "pattern"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "mcp-call"
                    ]
                  },
                  "server": {
                    "type": "string"
                  }
                },
                "required": [
                  "type",
                  "server"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "file-read"
                    ]
                  },
                  "extension": {
                    "type": "string"
                  }
                },
                "required": [
                  "type",
                  "extension"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "file-write"
                    ]
                  },
                  "extension": {
                    "type": "string"
                  }
                },
                "required": [
                  "type",
                  "extension"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "javascript"
                    ]
                  },
                  "code": {
                    "type": "string"
                  }
                },
                "required": [
                  "type",
                  "code"
                ],
                "additionalProperties": false,
                "description": "Evaluate a JavaScript expression against a successful text-file edit. The file variable has absolute path and sizeBytes fields."
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "after-compaction"
                    ]
                  }
                },
                "required": [
                  "type"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "resource-pressure"
                    ]
                  },
                  "level": {
                    "type": "string",
                    "enum": [
                      "warning",
                      "floor",
                      "either"
                    ]
                  }
                },
                "required": [
                  "type",
                  "level"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "time-of-day"
                    ]
                  },
                  "after": {
                    "type": "string"
                  },
                  "before": {
                    "type": "string"
                  }
                },
                "required": [
                  "type",
                  "after",
                  "before"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "new-day"
                    ]
                  }
                },
                "required": [
                  "type"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "interval"
                    ]
                  },
                  "minutes": {
                    "anyOf": [
                      {
                        "type": "number"
                      },
                      {
                        "type": "string",
                        "enum": [
                          "NaN"
                        ]
                      },
                      {
                        "type": "string",
                        "enum": [
                          "Infinity"
                        ]
                      },
                      {
                        "type": "string",
                        "enum": [
                          "-Infinity"
                        ]
                      }
                    ]
                  }
                },
                "required": [
                  "type",
                  "minutes"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "script"
                    ]
                  },
                  "command": {
                    "type": "string"
                  }
                },
                "required": [
                  "type",
                  "command"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "repeated-tool"
                    ]
                  },
                  "tool": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "count": {
                    "anyOf": [
                      {
                        "anyOf": [
                          {
                            "type": "number"
                          },
                          {
                            "type": "string",
                            "enum": [
                              "NaN"
                            ]
                          },
                          {
                            "type": "string",
                            "enum": [
                              "Infinity"
                            ]
                          },
                          {
                            "type": "string",
                            "enum": [
                              "-Infinity"
                            ]
                          }
                        ]
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "kind": {
                    "anyOf": [
                      {
                        "type": "string",
                        "enum": [
                          "identical",
                          "failure"
                        ]
                      },
                      {
                        "type": "null"
                      }
                    ]
                  }
                },
                "required": [
                  "type"
                ],
                "additionalProperties": false,
                "description": "Fires when the agent calls the same tool with the same arguments (or to the same failing target) N times in a row. The harness detects the loop; this hook only selects which loops a nudge answers."
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "session-restarted"
                    ]
                  }
                },
                "required": [
                  "type"
                ],
                "additionalProperties": false,
                "description": "Fires once when a provider recovery restarts the session. Replaces the hardcoded restart notice."
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "empty-turn"
                    ]
                  },
                  "count": {
                    "anyOf": [
                      {
                        "anyOf": [
                          {
                            "type": "number"
                          },
                          {
                            "type": "string",
                            "enum": [
                              "NaN"
                            ]
                          },
                          {
                            "type": "string",
                            "enum": [
                              "Infinity"
                            ]
                          },
                          {
                            "type": "string",
                            "enum": [
                              "-Infinity"
                            ]
                          }
                        ]
                      },
                      {
                        "type": "null"
                      }
                    ]
                  }
                },
                "required": [
                  "type"
                ],
                "additionalProperties": false,
                "description": "Fires when a turn ends with no reply and no tool call. count 1 is the first recovery, 2 the diagnostic."
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "announced-tool"
                    ]
                  }
                },
                "required": [
                  "type"
                ],
                "additionalProperties": false,
                "description": "Fires when a turn promised a tool call and never made one."
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "finish-audit"
                    ]
                  }
                },
                "required": [
                  "type"
                ],
                "additionalProperties": false,
                "description": "Fires when the finish audit finds the goal not fully achieved and the agent must continue."
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "ask"
                    ]
                  },
                  "question": {
                    "type": "string"
                  }
                },
                "required": [
                  "type",
                  "question"
                ],
                "additionalProperties": false,
                "description": "Ask a model a single yes/no question with the conversation's current context as prefix. The nudge fires when the answer contains yes."
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "prompt"
                    ]
                  },
                  "request": {
                    "type": "string"
                  }
                },
                "required": [
                  "type",
                  "request"
                ],
                "additionalProperties": false,
                "description": "Ask a model to write this nudge's body for the conversation's current context, quoting it in a fenced block. The fenced body becomes the delivered text."
              }
            ],
            "description": "A harness-owned event selector. Script hooks fire when their command exits successfully."
          },
          "text": {
            "type": "string"
          },
          "script": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "description": "Optional command whose bounded stdout is appended to the instruction at delivery time."
          },
          "spammable": {
            "anyOf": [
              {
                "type": "boolean"
              },
              {
                "type": "null"
              }
            ],
            "description": "Repeat as often as the trigger fires. Off by default: a nudge is delivered at most once per 30 minutes and at most once per context epoch."
          },
          "minSubordinates": {
            "anyOf": [
              {
                "anyOf": [
                  {
                    "type": "number"
                  },
                  {
                    "type": "string",
                    "enum": [
                      "NaN"
                    ]
                  },
                  {
                    "type": "string",
                    "enum": [
                      "Infinity"
                    ]
                  },
                  {
                    "type": "string",
                    "enum": [
                      "-Infinity"
                    ]
                  }
                ]
              },
              {
                "type": "null"
              }
            ],
            "description": "Deliver only when the officer has at least this many direct subordinates."
          },
          "requireNoSubordinates": {
            "anyOf": [
              {
                "type": "boolean"
              },
              {
                "type": "null"
              }
            ],
            "description": "Deliver only when the officer has no direct subordinates."
          },
          "tokenRate": {
            "anyOf": [
              {
                "type": "object",
                "properties": {
                  "tokens": {
                    "anyOf": [
                      {
                        "type": "number"
                      },
                      {
                        "type": "string",
                        "enum": [
                          "NaN"
                        ]
                      },
                      {
                        "type": "string",
                        "enum": [
                          "Infinity"
                        ]
                      },
                      {
                        "type": "string",
                        "enum": [
                          "-Infinity"
                        ]
                      }
                    ]
                  },
                  "windowSeconds": {
                    "anyOf": [
                      {
                        "type": "number"
                      },
                      {
                        "type": "string",
                        "enum": [
                          "NaN"
                        ]
                      },
                      {
                        "type": "string",
                        "enum": [
                          "Infinity"
                        ]
                      },
                      {
                        "type": "string",
                        "enum": [
                          "-Infinity"
                        ]
                      }
                    ]
                  }
                },
                "required": [
                  "tokens",
                  "windowSeconds"
                ],
                "additionalProperties": false
              },
              {
                "type": "null"
              }
            ],
            "description": "Deliver only when the agent generated at least this many tokens in the last windowSeconds."
          },
          "requireTmpFolder": {
            "anyOf": [
              {
                "type": "boolean"
              },
              {
                "type": "null"
              }
            ],
            "description": "Deliver only when the project folder contains a ./tmp directory."
          },
          "clearChat": {
            "anyOf": [
              {
                "type": "boolean"
              },
              {
                "type": "null"
              }
            ],
            "description": "Clear the officer's chat before inserting the nudge."
          },
          "forceCompaction": {
            "anyOf": [
              {
                "type": "boolean"
              },
              {
                "type": "null"
              }
            ],
            "description": "Force a context compaction before inserting the nudge."
          },
          "stopOfficer": {
            "anyOf": [
              {
                "type": "boolean"
              },
              {
                "type": "null"
              }
            ],
            "description": "Stop the officer (interrupt its current work)."
          },
          "sleepSeconds": {
            "anyOf": [
              {
                "anyOf": [
                  {
                    "type": "number"
                  },
                  {
                    "type": "string",
                    "enum": [
                      "NaN"
                    ]
                  },
                  {
                    "type": "string",
                    "enum": [
                      "Infinity"
                    ]
                  },
                  {
                    "type": "string",
                    "enum": [
                      "-Infinity"
                    ]
                  }
                ]
              },
              {
                "type": "null"
              }
            ],
            "description": "Put the officer to sleep for this many seconds before inserting the nudge."
          },
          "cooldownSeconds": {
            "anyOf": [
              {
                "anyOf": [
                  {
                    "type": "number"
                  },
                  {
                    "type": "string",
                    "enum": [
                      "NaN"
                    ]
                  },
                  {
                    "type": "string",
                    "enum": [
                      "Infinity"
                    ]
                  },
                  {
                    "type": "string",
                    "enum": [
                      "-Infinity"
                    ]
                  }
                ]
              },
              {
                "type": "null"
              }
            ],
            "description": "Seconds this nudge stays silent after firing, independent of the quiet rule."
          },
          "default": {
            "anyOf": [
              {
                "type": "boolean"
              },
              {
                "type": "null"
              }
            ],
            "description": "True for shipped default nudges. The UI badges these and can hide them."
          }
        },
        "required": [
          "id",
          "name",
          "hook",
          "text"
        ],
        "additionalProperties": false
      }
    }
  },
  "outputSchema": {
    "type": "string"
  }
}),
sideEffect: "idempotent-write",
load: () => import("../nudge"),

}),
deps: [ToolRegistry.node, PermissionV2.node, AgentConfigStore.node, AgentV2.node, NudgeService.node],
})
