// Generated by packages/core/script/deferred-builtins.ts. Do not edit.
import { ToolDefinition } from "@novaclaw/llm"
import { makeLocationNode } from "../../effect/app-node"
import { LazyBuiltin } from "../lazy-builtin"
import { AgentConfigStore } from "../../agent-config-store"
import { PermissionV2 } from "../../permission"
import { ToolRegistry } from ".././registry"

export const node = makeLocationNode({
name: "tool/nudge",
layer: LazyBuiltin.layer({
definition: new ToolDefinition({
  "name": "nudge",
  "description": "List, view, add, edit, or delete an officer's personal Nudges — the targeted instructions that fire inside its own sessions. Nova may manage any officer's nudges. Other officers may manage only their own. A nudge can use a new-day, time, tool, file, compaction, resource, or script hook; its optional script appends bounded dynamic stdout at delivery time.",
  "inputSchema": {
    "anyOf": [
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "list"
            ]
          },
          "target": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "required": [
          "op"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "view"
            ]
          },
          "id": {
            "type": "string"
          },
          "target": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "required": [
          "op",
          "id"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "add",
              "edit"
            ]
          },
          "target": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "nudge": {
            "$ref": "#/$defs/ConfigV2.Nudge"
          }
        },
        "required": [
          "op",
          "nudge"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "delete"
            ]
          },
          "id": {
            "type": "string"
          },
          "target": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "required": [
          "op",
          "id"
        ],
        "additionalProperties": false
      }
    ],
    "$defs": {
      "ConfigV2.Nudge": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "enabled": {
            "anyOf": [
              {
                "type": "boolean"
              },
              {
                "type": "null"
              }
            ]
          },
          "hook": {
            "anyOf": [
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "text-match"
                    ]
                  },
                  "pattern": {
                    "type": "string"
                  }
                },
                "required": [
                  "type",
                  "pattern"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "write-match"
                    ]
                  },
                  "pattern": {
                    "type": "string"
                  }
                },
                "required": [
                  "type",
                  "pattern"
                ],
                "additionalProperties": false,
                "description": "Fires when the content a writing tool is about to write matches the pattern. Never tested against a tool's OUTPUT, so text the agent merely read cannot fire it."
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "tool-call"
                    ]
                  },
                  "tool": {
                    "type": "string"
                  }
                },
                "required": [
                  "type",
                  "tool"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "mcp-call"
                    ]
                  },
                  "server": {
                    "type": "string"
                  }
                },
                "required": [
                  "type",
                  "server"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "file-read"
                    ]
                  },
                  "extension": {
                    "type": "string"
                  }
                },
                "required": [
                  "type",
                  "extension"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "file-write"
                    ]
                  },
                  "extension": {
                    "type": "string"
                  }
                },
                "required": [
                  "type",
                  "extension"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "after-compaction"
                    ]
                  }
                },
                "required": [
                  "type"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "resource-pressure"
                    ]
                  },
                  "level": {
                    "type": "string",
                    "enum": [
                      "warning",
                      "floor",
                      "either"
                    ]
                  }
                },
                "required": [
                  "type",
                  "level"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "time-of-day"
                    ]
                  },
                  "after": {
                    "type": "string"
                  },
                  "before": {
                    "type": "string"
                  }
                },
                "required": [
                  "type",
                  "after",
                  "before"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "new-day"
                    ]
                  }
                },
                "required": [
                  "type"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "script"
                    ]
                  },
                  "command": {
                    "type": "string"
                  }
                },
                "required": [
                  "type",
                  "command"
                ],
                "additionalProperties": false
              }
            ],
            "description": "A harness-owned event selector. Script hooks fire when their command exits successfully."
          },
          "text": {
            "type": "string"
          },
          "script": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "description": "Optional command whose bounded stdout is appended to the instruction at delivery time."
          },
          "spammable": {
            "anyOf": [
              {
                "type": "boolean"
              },
              {
                "type": "null"
              }
            ],
            "description": "Repeat as often as the trigger fires. Off by default: a nudge is delivered at most once per 30 minutes and at most once per context epoch."
          }
        },
        "required": [
          "id",
          "name",
          "hook",
          "text"
        ],
        "additionalProperties": false
      }
    }
  },
  "outputSchema": {
    "type": "string"
  }
}),
sideEffect: "idempotent-write",
load: () => import("../nudge"),

}),
deps: [ToolRegistry.node, PermissionV2.node, AgentConfigStore.node],
})
