// Generated by packages/core/script/deferred-builtins.ts. Do not edit.
import { ToolDefinition } from "@novaclaw/llm"
import { makeLocationNode } from "../../effect/app-node"
import { LazyBuiltin } from "../lazy-builtin"
import { EventV2 } from "../../event"
import { PermissionV2 } from "../../permission"
import { SessionStore } from "../../session/store"
import { SessionAutoGrant } from "../../session/auto-grant"
import { ToolRegistry } from ".././registry"

export const node = makeLocationNode({
name: "tool/permission",
layer: LazyBuiltin.layer({
definition: new ToolDefinition({
  "name": "permission",
  "description": "Set YOUR OWN permission level for this chat, and own it. Lower yourself to the least capability the work actually needs, and raise yourself back — in writing — when you need more. {\"op\":\"lower\",\"mode\":\"plan\",\"justification\":\"reading the codebase first; I will not change anything yet\"} · {\"op\":\"raise\",\"mode\":\"bypass\",\"justification\":\"the plan is agreed; I now need to edit src/ to apply it\"}. LOWERING is always permitted and never asks. RAISING can never go above the mode the user picked for this chat (and never above bypass when nobody is attending), so it is a way back to what you had, not a way past it; the refusal names the bound when it bites. A `justification` is required on every call — that is the point of the tool, not paperwork. The level applies to the very next tool call and to every session you spawn afterwards, and survives an instance restart.",
  "inputSchema": {
    "type": "object",
    "properties": {
      "op": {
        "type": "string",
        "enum": [
          "raise",
          "lower"
        ],
        "description": "\"lower\" to give up capability (always permitted, never asks), \"raise\" to take it back. The word must match the direction of `mode` on the ladder, or the call is refused."
      },
      "mode": {
        "type": "string",
        "enum": [
          "plan",
          "ask",
          "surgical",
          "bypass",
          "yolo"
        ],
        "description": "The level you are taking, from least to most capable: plan (read only) · ask (every change asks the user) · surgical (edits, no whole-file overwrites) · bypass (act freely inside this chat's folder) · yolo (act freely anywhere on this computer)."
      },
      "justification": {
        "type": "string",
        "description": "WHY, in your own words — what you are about to do and why this level is needed for it. It goes on the record for the user to read afterwards. It is required; a blank or perfunctory one is refused."
      }
    },
    "required": [
      "op",
      "mode",
      "justification"
    ],
    "additionalProperties": false
  },
  "outputSchema": {
    "type": "object",
    "properties": {
      "changed": {
        "type": "boolean"
      },
      "mode": {
        "type": "string",
        "enum": [
          "plan",
          "ask",
          "surgical",
          "bypass",
          "yolo"
        ]
      },
      "previous": {
        "type": "string",
        "enum": [
          "plan",
          "ask",
          "surgical",
          "bypass",
          "yolo"
        ]
      },
      "ceiling": {
        "type": "string",
        "enum": [
          "plan",
          "ask",
          "surgical",
          "bypass",
          "yolo"
        ]
      }
    },
    "required": [
      "changed",
      "mode",
      "previous",
      "ceiling"
    ],
    "additionalProperties": false
  }
}),
sideEffect: "external-unknown",
load: () => import("../permission"),

}),
deps: [ToolRegistry.node, PermissionV2.node, SessionStore.node, SessionAutoGrant.node, EventV2.node],
})
