// Generated by packages/core/script/deferred-builtins.ts. Do not edit.
import { ToolDefinition } from "@novaclaw/llm"
import { makeLocationNode } from "../../effect/app-node"
import { LazyBuiltin } from "../lazy-builtin"
import { Config } from "../../config"
import { ToolRegistry } from ".././registry"
import { sharingEnabled as available } from ".././profile-availability"

export const node = makeLocationNode({
name: "tool/profile",
layer: LazyBuiltin.layer({
definition: new ToolDefinition({
  "name": "profile",
  "description": "Look up the user's own profile — the name and background (\"about me\") they have made available to you. Call this when you need to know who you are helping (to address them by name, or to tailor an answer to their role, expertise, or stated preferences). The user controls what is here; treat it as trusted context they volunteered.",
  "inputSchema": {
    "anyOf": [
      {
        "type": "object"
      },
      {
        "type": "array"
      }
    ]
  },
  "outputSchema": {
    "type": "object",
    "properties": {
      "name": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "about": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      }
    },
    "additionalProperties": false
  }
}),
sideEffect: "external-unknown",
load: () => import("../profile"),
available,
}),
deps: [ToolRegistry.node, Config.node],
})
