// Generated by packages/core/script/deferred-builtins.ts. Do not edit.
import { ToolDefinition } from "@novaclaw/llm"
import { makeLocationNode } from "../../effect/app-node"
import { LazyBuiltin } from "../lazy-builtin"
import { Location } from "../../location"
import { PermissionV2 } from "../../permission"
import { AppProcess } from "../../process"
import { SettingsConfigStore } from "../../settings-config-store"
import { ToolRegistry } from ".././registry"

export const node = makeLocationNode({
name: "tool/quality-provision",
layer: LazyBuiltin.layer({
definition: new ToolDefinition({
  "name": "quality_provision",
  "description": "Provision this project's QUALITY commands (QE): scan the project's own manifests — package.json, Cargo.toml, go.mod, pyproject.toml, requirements.txt, setup.py, Makefile, CMakeLists.txt, build.gradle, pom.xml, *.sln, *.csproj, Gemfile — for typecheck/test/lint commands, verify each candidate actually runs (a red check still verifies — only a missing toolchain drops it), and save the result to the instance quality settings (the record Settings → Quality edits). Pass explicit `commands` to override or fill gaps; a per-file `check` or `syntax` command may use `{file}` for the path of the file that was just written. Newly saved commands activate for future sessions.",
  "inputSchema": {
    "type": "object",
    "properties": {
      "commands": {
        "anyOf": [
          {
            "$ref": "#/$defs/QualityCommands"
          },
          {
            "type": "null"
          }
        ],
        "description": "Explicit command overrides (win over the scan). Use when the scan missed something or proposed the wrong runner. `check` and `syntax` run PER WRITTEN FILE, so give them a `{file}` placeholder (e.g. `ruff check {file}`); `typecheck`, `test` and `lint` are whole-project and take no file."
      },
      "verify": {
        "anyOf": [
          {
            "type": "boolean"
          },
          {
            "type": "null"
          }
        ],
        "description": "Run each candidate once to verify the toolchain exists (default true). Failing checks still count as verified — only 'command not found' drops a candidate."
      },
      "write": {
        "anyOf": [
          {
            "type": "boolean"
          },
          {
            "type": "null"
          }
        ],
        "description": "Save the resolved commands to this instance's quality settings (default true)."
      }
    },
    "additionalProperties": false,
    "$defs": {
      "QualityCommands": {
        "type": "object",
        "properties": {
          "syntax": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "check": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "typecheck": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "test": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "lint": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "additionalProperties": false
      }
    }
  },
  "outputSchema": {
    "type": "object",
    "properties": {
      "commands": {
        "$ref": "#/$defs/QualityCommands"
      },
      "dropped": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "evidence": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "written": {
        "type": "boolean"
      }
    },
    "required": [
      "commands",
      "dropped",
      "evidence",
      "written"
    ],
    "additionalProperties": false,
    "$defs": {
      "QualityCommands": {
        "type": "object",
        "properties": {
          "syntax": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "check": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "typecheck": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "test": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "lint": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "additionalProperties": false
      }
    }
  }
}),
sideEffect: "external-unknown",
load: () => import("../quality-provision"),

}),
deps: [ToolRegistry.node, PermissionV2.node, Location.node, AppProcess.node, SettingsConfigStore.node],
})
