// Generated by packages/core/script/deferred-builtins.ts. Do not edit.
import { ToolDefinition } from "@novaclaw/llm"
import { makeLocationNode } from "../../effect/app-node"
import { LazyBuiltin } from "../lazy-builtin"
import { LocationMutation } from "../../location-mutation"
import { PermissionV2 } from "../../permission"
import { ToolRegistry } from ".././registry"

export const node = makeLocationNode({
name: "tool/read-hex",
layer: LazyBuiltin.layer({
definition: new ToolDefinition({
  "name": "read-hex",
  "description": "Inspect a BINARY file as a hex dump: 16 hex bytes per line, `;` starts a comment carrying the line's offset and ascii gloss. Reads a window of `length` bytes at `offset` — it pages, so it works on multi-GB images. The output format is exactly what `write-hex` accepts, so you can edit a dump and write it back. Use this (not `read`) for .bin/.iso/.o/object files/images and any non-text file.",
  "inputSchema": {
    "type": "object",
    "properties": {
      "filename": {
        "type": "string",
        "description": "File to inspect. Relative paths resolve within the active Location."
      },
      "offset": {
        "anyOf": [
          {
            "anyOf": [
              {
                "type": "number"
              },
              {
                "type": "string",
                "enum": [
                  "NaN"
                ]
              },
              {
                "type": "string",
                "enum": [
                  "Infinity"
                ]
              },
              {
                "type": "string",
                "enum": [
                  "-Infinity"
                ]
              }
            ],
            "description": "Byte offset to start reading from (default 0)."
          },
          {
            "type": "null"
          }
        ]
      },
      "length": {
        "anyOf": [
          {
            "anyOf": [
              {
                "type": "number"
              },
              {
                "type": "string",
                "enum": [
                  "NaN"
                ]
              },
              {
                "type": "string",
                "enum": [
                  "Infinity"
                ]
              },
              {
                "type": "string",
                "enum": [
                  "-Infinity"
                ]
              }
            ],
            "description": "Number of bytes to read (default 1024, max 8192 per call — page with `offset` for more)."
          },
          {
            "type": "null"
          }
        ]
      }
    },
    "required": [
      "filename"
    ],
    "additionalProperties": false
  },
  "outputSchema": {
    "type": "object",
    "properties": {
      "content": {
        "type": "string"
      },
      "offset": {
        "anyOf": [
          {
            "type": "number"
          },
          {
            "type": "string",
            "enum": [
              "NaN"
            ]
          },
          {
            "type": "string",
            "enum": [
              "Infinity"
            ]
          },
          {
            "type": "string",
            "enum": [
              "-Infinity"
            ]
          }
        ]
      },
      "bytes": {
        "anyOf": [
          {
            "type": "number"
          },
          {
            "type": "string",
            "enum": [
              "NaN"
            ]
          },
          {
            "type": "string",
            "enum": [
              "Infinity"
            ]
          },
          {
            "type": "string",
            "enum": [
              "-Infinity"
            ]
          }
        ]
      },
      "size": {
        "anyOf": [
          {
            "type": "number"
          },
          {
            "type": "string",
            "enum": [
              "NaN"
            ]
          },
          {
            "type": "string",
            "enum": [
              "Infinity"
            ]
          },
          {
            "type": "string",
            "enum": [
              "-Infinity"
            ]
          }
        ]
      },
      "next": {
        "anyOf": [
          {
            "anyOf": [
              {
                "type": "number"
              },
              {
                "type": "string",
                "enum": [
                  "NaN"
                ]
              },
              {
                "type": "string",
                "enum": [
                  "Infinity"
                ]
              },
              {
                "type": "string",
                "enum": [
                  "-Infinity"
                ]
              }
            ]
          },
          {
            "type": "null"
          }
        ]
      }
    },
    "required": [
      "content",
      "offset",
      "bytes",
      "size"
    ],
    "additionalProperties": false
  }
}),
sideEffect: "read",
load: () => import("../read-hex"),

}),
deps: [ToolRegistry.node, LocationMutation.node, PermissionV2.node],
})
