// Generated by packages/core/script/deferred-builtins.ts. Do not edit.
import { ToolDefinition } from "@novaclaw/llm"
import { makeLocationNode } from "../../effect/app-node"
import { LazyBuiltin } from "../lazy-builtin"
import { Global } from "../../global"
import { PermissionV2 } from "../../permission"
import { ToolRegistry } from ".././registry"

export const node = makeLocationNode({
name: "tool/recipe",
layer: LazyBuiltin.layer({
definition: new ToolDefinition({
  "name": "recipe",
  "description": "Author and read RECIPES — the folders of prose this product is built on (a recipe.md prompt plus its assets). A recipe carries the INTENT of a thing to build, so an agent can cook it fresh later; it is not code and never carries settings. Ops: {\"op\":\"list\"} — every recipe on this install · {\"op\":\"read\",\"slug\":\"hello-c\"} — one recipe's full text · {\"op\":\"save\",\"name\":\"…\",\"prompt\":\"…\",\"description\":\"…\",\"needs\":[\"a C compiler\"],\"produces\":[\"hello.c\"]} — write a new one (add slug to replace an existing one instead). Saving returns the recipe's folder — put any assets it needs there with the write tool. Saving asks the user first, because a recipe becomes a future session's prompt.",
  "inputSchema": {
    "anyOf": [
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "list"
            ]
          }
        },
        "required": [
          "op"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "read"
            ]
          },
          "slug": {
            "type": "string",
            "description": "The recipe's folder name, exactly as `list` reported it"
          }
        },
        "required": [
          "op",
          "slug"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "save"
            ]
          },
          "name": {
            "type": "string",
            "description": "The recipe's title in plain words, e.g. \"Compile and run a C program\""
          },
          "prompt": {
            "type": "string",
            "description": "THE RECIPE ITSELF: the instructions for cooking the thing, in prose a normal person can read and edit. Write the INTENT and the acceptance test, not code and not settings — a capable agent will re-derive a working artifact from it years from now. Do not name your own machine's install paths."
          },
          "description": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "description": "One line shown beside the title in the recipe list"
          },
          "needs": {
            "anyOf": [
              {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              {
                "type": "null"
              }
            ],
            "description": "Host capabilities this recipe needs, each a short fact a person can check: [\"a C compiler\", \"python3\"]. This is the ONLY structured field a recipe may carry — it states what the recipe NEEDS, never what it gets."
          },
          "produces": {
            "anyOf": [
              {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              {
                "type": "null"
              }
            ],
            "description": "The files a FINISHED cook leaves in the folder: [\"clean.csv\", \"chart.html\"]. NovaClaw checks them itself after the cook and reports WORKING or NOT WORKING, so a recipe that declares them has an outcome a machine can read instead of an opinion. Plain file names only — no paths outside the folder, no commands. Only name files your PROMPT actually asks for, or every healthy run will be reported as broken."
          },
          "slug": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "description": "Folder name of an EXISTING recipe to replace. Omit it to create a new recipe."
          }
        },
        "required": [
          "op",
          "name",
          "prompt"
        ],
        "additionalProperties": false
      }
    ]
  },
  "outputSchema": {
    "type": "object",
    "properties": {
      "op": {
        "type": "string",
        "enum": [
          "list",
          "read",
          "save"
        ]
      },
      "slug": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "message": {
        "type": "string"
      }
    },
    "required": [
      "op",
      "message"
    ],
    "additionalProperties": false
  }
}),
sideEffect: "external-unknown",
load: () => import("../recipe"),

}),
deps: [ToolRegistry.node, PermissionV2.node, Global.node],
})
