// Generated by packages/core/script/deferred-builtins.ts. Do not edit.
import { ToolDefinition } from "@novaclaw/llm"
import { makeLocationNode } from "../../effect/app-node"
import { LazyBuiltin } from "../lazy-builtin"
import { EventV2 } from "../../event"
import { PermissionV2 } from "../../permission"
import { ToolRegistry } from ".././registry"

export const node = makeLocationNode({
name: "tool/register-app",
layer: LazyBuiltin.layer({
definition: new ToolDefinition({
  "name": "register-app",
  "description": "Register (or update) an app tile on the user's home screen. An app is a LAUNCHER manifest: it opens a built-in app by route id (contacts, notes, files, calendar, recipes, skills, registry, debug, trash, terminal), an external URL, or a new chat pre-filled with a prompt — use open_type 'prompt' to turn a repeatable request into a one-tap app. Reusing an id updates that app.",
  "inputSchema": {
    "type": "object",
    "properties": {
      "title": {
        "type": "string",
        "description": "Display title for the app tile (e.g. 'Stock Prices')"
      },
      "id": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "description": "Lowercase slug id (a-z, 0-9, -, _). Derived from the title when omitted; reusing an id updates that app."
      },
      "subtitle": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "description": "One-line description shown on the tile"
      },
      "icon": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "description": "Sprite icon name (optional; a default is used)"
      },
      "accent": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "description": "CSS accent color for the tile, e.g. #38bdf8 (optional)"
      },
      "open_type": {
        "type": "string",
        "enum": [
          "route",
          "url",
          "prompt"
        ],
        "description": "What the tile opens: 'route' = a built-in app selected by id, 'url' = an external http(s) page, 'prompt' = a new chat pre-filled with this prompt"
      },
      "route_id": {
        "anyOf": [
          {
            "type": "string",
            "enum": [
              "contacts",
              "notes",
              "files",
              "calendar",
              "recipes",
              "skills",
              "registry",
              "debug",
              "trash",
              "terminal"
            ]
          },
          {
            "type": "null"
          }
        ],
        "description": "Built-in app to open when open_type is 'route'. Choose one of: contacts, notes, files, calendar, recipes, skills, registry, debug, trash, terminal"
      },
      "open_value": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "description": "External URL or prompt text when open_type is 'url' or 'prompt'. Example: open_type 'prompt' + open_value 'Show me today's stock prices for my portfolio'"
      }
    },
    "required": [
      "title",
      "open_type"
    ],
    "additionalProperties": false
  },
  "outputSchema": {
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "title": {
        "type": "string"
      }
    },
    "required": [
      "id",
      "title"
    ],
    "additionalProperties": false
  }
}),
sideEffect: "external-unknown",
load: () => import("../register-app"),

}),
deps: [ToolRegistry.node, PermissionV2.node, EventV2.node],
})
