// Generated by packages/core/script/deferred-builtins.ts. Do not edit.
import { ToolDefinition } from "@novaclaw/llm"
import { makeLocationNode } from "../../effect/app-node"
import { LazyBuiltin } from "../lazy-builtin"
import { ResourcePressureContext } from "../../resource-pressure-context"
import { ToolRegistry } from ".././registry"

export const node = makeLocationNode({
name: "tool/resource-status",
layer: LazyBuiltin.layer({
definition: new ToolDefinition({
  "name": "resource_status",
  "description": "Inspect this instance's live memory pressure and disk headroom. Use after a resource warning or cleanup to confirm whether pressure returned to normal.",
  "inputSchema": {
    "anyOf": [
      {
        "type": "object"
      },
      {
        "type": "array"
      }
    ]
  },
  "outputSchema": {
    "type": "object",
    "properties": {
      "lines": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "required": [
      "lines"
    ],
    "additionalProperties": false
  }
}),
sideEffect: "external-unknown",
load: () => import("../resource-status"),

}),
deps: [ToolRegistry.node, ResourcePressureContext.node],
})
