// Generated by packages/core/script/deferred-builtins.ts. Do not edit.
import { ToolDefinition } from "@novaclaw/llm"
import { makeLocationNode } from "../../effect/app-node"
import { LazyBuiltin } from "../lazy-builtin"
import { Database } from "../../database/database"
import { PermissionV2 } from "../../permission"
import { Snapshot } from "../../snapshot"
import { ToolRegistry } from ".././registry"

export const node = makeLocationNode({
name: "tool/revert",
layer: LazyBuiltin.layer({
definition: new ToolDefinition({
  "name": "revert",
  "description": "UNDO file changes by restoring files to an earlier snapshot (git-backed, captured every step). Default undoes your last file-changing step; `steps: N` undoes the last N; `steps: 0` undoes only the current step's changes so far. Restores file EDITS — deletions are restored from the Trash instead. Use when an edit made things worse and you want a known-good state back.",
  "inputSchema": {
    "type": "object",
    "properties": {
      "steps": {
        "anyOf": [
          {
            "type": "integer",
            "allOf": [
              {
                "minimum": 0
              },
              {
                "maximum": 50
              }
            ]
          },
          {
            "type": "null"
          }
        ],
        "description": "How many of your most recent file-CHANGING steps to undo (default 1). 0 undoes only the changes made so far in the CURRENT step."
      },
      "messageID": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "description": "Alternative to steps: revert every file change made after this message id."
      }
    },
    "additionalProperties": false
  },
  "outputSchema": {
    "type": "object",
    "properties": {
      "files": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "count": {
        "anyOf": [
          {
            "type": "number"
          },
          {
            "type": "string",
            "enum": [
              "NaN"
            ]
          },
          {
            "type": "string",
            "enum": [
              "Infinity"
            ]
          },
          {
            "type": "string",
            "enum": [
              "-Infinity"
            ]
          }
        ]
      }
    },
    "required": [
      "files",
      "count"
    ],
    "additionalProperties": false
  }
}),
sideEffect: "external-unknown",
load: () => import("../revert"),

}),
deps: [ToolRegistry.node, PermissionV2.node, Snapshot.node, Database.node],
})
