// Generated by packages/core/script/deferred-builtins.ts. Do not edit.
import { ToolDefinition } from "@novaclaw/llm"
import { makeLocationNode } from "../../effect/app-node"
import { LazyBuiltin } from "../lazy-builtin"
import { Database } from "../../database/database"
import { ToolRegistry } from ".././registry"

export const node = makeLocationNode({
name: "tool/schedule",
layer: LazyBuiltin.layer({
definition: new ToolDefinition({
  "name": "schedule",
  "description": "List your scheduled work, confirm one active window complete, or disable a recurring schedule. A schedule nudge gives the scheduleId and occurrenceMillis needed for confirmation.",
  "inputSchema": {
    "anyOf": [
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "list"
            ]
          }
        },
        "required": [
          "op"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "confirm"
            ]
          },
          "scheduleId": {
            "type": "string"
          },
          "occurrenceMillis": {
            "type": "number"
          }
        },
        "required": [
          "op",
          "scheduleId",
          "occurrenceMillis"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "disable"
            ]
          },
          "scheduleId": {
            "type": "string"
          }
        },
        "required": [
          "op",
          "scheduleId"
        ],
        "additionalProperties": false
      }
    ]
  },
  "outputSchema": {
    "type": "string"
  }
}),
sideEffect: "idempotent-write",
load: () => import("../schedule"),

}),
deps: [ToolRegistry.node, Database.node],
})
