// Generated by packages/core/script/deferred-builtins.ts. Do not edit.
import { ToolDefinition } from "@novaclaw/llm"
import { makeLocationNode } from "../../effect/app-node"
import { LazyBuiltin } from "../lazy-builtin"
import { PermissionV2 } from "../../permission"
import { SessionComponentRegistry } from "../../session/component-registry"
import { SessionExecutionAttempt } from "../../session/execution-attempt"
import { SessionStore } from "../../session/store"
import { ToolRegistry } from ".././registry"

export const node = makeLocationNode({
name: "tool/session",
layer: LazyBuiltin.layer({
definition: new ToolDefinition({
  "name": "session",
  "description": "Inspect session components and manage YOUR OWN through one typed registry. Operations: schema describes available kinds and their exact JSON shape; read gets one singleton or set member; list gets every member of one kind; set validates and stores a value; remove clears it so inheritance can resume. Read/list may name any session in this instance; prompt-bearing values require privileged approval. Set/remove remain self-only and reject a target. Start with schema when unsure. Component ids are only for set-valued kinds.",
  "inputSchema": {
    "anyOf": [
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "schema"
            ]
          },
          "kind": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "description": "One component kind to describe. Omit to survey every component this kernel exposes."
          }
        },
        "required": [
          "op"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "read"
            ]
          },
          "sessionID": {
            "anyOf": [
              {
                "type": "string",
                "allOf": [
                  {
                    "pattern": "^ses"
                  }
                ]
              },
              {
                "type": "null"
              }
            ],
            "description": "Session to inspect. Omit for your own session."
          },
          "kind": {
            "type": "string"
          },
          "id": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "required": [
          "op",
          "kind"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "list"
            ]
          },
          "sessionID": {
            "anyOf": [
              {
                "type": "string",
                "allOf": [
                  {
                    "pattern": "^ses"
                  }
                ]
              },
              {
                "type": "null"
              }
            ],
            "description": "Session to inspect. Omit for your own session."
          },
          "kind": {
            "type": "string"
          }
        },
        "required": [
          "op",
          "kind"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "set"
            ]
          },
          "sessionID": {
            "anyOf": [
              {
                "type": "string",
                "allOf": [
                  {
                    "pattern": "^ses"
                  }
                ]
              },
              {
                "type": "null"
              }
            ],
            "description": "Reserved for a future descendant-write capability. Omit: writes are self-only."
          },
          "kind": {
            "type": "string"
          },
          "id": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "value": {}
        },
        "required": [
          "op",
          "kind",
          "value"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "remove"
            ]
          },
          "sessionID": {
            "anyOf": [
              {
                "type": "string",
                "allOf": [
                  {
                    "pattern": "^ses"
                  }
                ]
              },
              {
                "type": "null"
              }
            ],
            "description": "Reserved for a future descendant-write capability. Omit: writes are self-only."
          },
          "kind": {
            "type": "string"
          },
          "id": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "required": [
          "op",
          "kind"
        ],
        "additionalProperties": false
      }
    ]
  },
  "outputSchema": {
    "type": "object",
    "properties": {
      "op": {
        "type": "string"
      },
      "message": {
        "type": "string"
      },
      "foreign": {
        "anyOf": [
          {
            "type": "boolean"
          },
          {
            "type": "null"
          }
        ]
      }
    },
    "required": [
      "op",
      "message"
    ],
    "additionalProperties": false
  }
}),
sideEffect: "external-unknown",
load: () => import("../session"),

}),
deps: [
    ToolRegistry.node,
    SessionComponentRegistry.node,
    PermissionV2.node,
    SessionStore.node,
    SessionExecutionAttempt.node,
  ],
})
