// Generated by packages/core/script/deferred-builtins.ts. Do not edit.
import { ToolDefinition } from "@novaclaw/llm"
import { makeLocationNode } from "../../effect/app-node"
import { LazyBuiltin } from "../lazy-builtin"
import { LocationMutation } from "../../location-mutation"
import { PermissionV2 } from "../../permission"
import { ToolRegistry } from ".././registry"

export const node = makeLocationNode({
name: "tool/trash",
layer: LazyBuiltin.layer({
definition: new ToolDefinition({
  "name": "trash",
  "description": "Safely delete a file or directory: moves it into a dated Trash store (restorable for the configured retention period) instead of destroying it. ALWAYS prefer this over `rm`/`del` in bash — the user can restore trashed items, and so can you if a deletion turns out wrong. Returns the trash id needed to restore.",
  "inputSchema": {
    "type": "object",
    "properties": {
      "path": {
        "type": "string",
        "description": "File or directory to delete SAFELY (moved to a restorable Trash for the configured retention period). Relative paths resolve within the active Location. Prefer this over `bash rm` for any deletion."
      }
    },
    "required": [
      "path"
    ],
    "additionalProperties": false
  },
  "outputSchema": {
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "originalPath": {
        "type": "string"
      },
      "type": {
        "type": "string",
        "enum": [
          "file",
          "directory"
        ]
      }
    },
    "required": [
      "id",
      "originalPath",
      "type"
    ],
    "additionalProperties": false
  }
}),
sideEffect: "idempotent-write",
load: () => import("../trash"),

}),
deps: [ToolRegistry.node, LocationMutation.node, PermissionV2.node],
})
