// Generated by packages/core/script/deferred-builtins.ts. Do not edit.
import { ToolDefinition } from "@novaclaw/llm"
import { makeLocationNode } from "../../effect/app-node"
import { LazyBuiltin } from "../lazy-builtin"
import { LocationMutation } from "../../location-mutation"
import { PermissionV2 } from "../../permission"
import { ToolRegistry } from ".././registry"

export const node = makeLocationNode({
name: "tool/write-hex",
layer: LazyBuiltin.layer({
definition: new ToolDefinition({
  "name": "write-hex",
  "description": "Patch bytes in a BINARY file at a byte offset (in place — the rest of the file is untouched; writing at the file size appends; a missing file is created only at offset 0). `data` is hex text — canonical input example:\n  4d 5a 90 00 03 00 00 00 ; first 8 bytes\n  ff fe\nAnything after \";\" is a comment, blank lines and indentation are ignored, and a byte may be written as 4d, 0x4d, 4dh or 4d-h — so read-hex output can be edited and written back verbatim. Use this (not `write`) for any non-text file.",
  "inputSchema": {
    "type": "object",
    "properties": {
      "filename": {
        "type": "string",
        "description": "File to patch (created when missing, but only at offset 0). Relative paths resolve within the active Location."
      },
      "offset": {
        "anyOf": [
          {
            "anyOf": [
              {
                "type": "number"
              },
              {
                "type": "string",
                "enum": [
                  "NaN"
                ]
              },
              {
                "type": "string",
                "enum": [
                  "Infinity"
                ]
              },
              {
                "type": "string",
                "enum": [
                  "-Infinity"
                ]
              }
            ],
            "description": "Byte offset to write at (default 0). At most the current file size — writing AT the size appends."
          },
          {
            "type": "null"
          }
        ]
      },
      "data": {
        "type": "string",
        "description": "Hex bytes to write, e.g. \"4d 5a 90 00 ; patched header\". Anything after \";\" on a line is a comment; blank lines and indentation are ignored; a byte may be written as 4d, 0x4d, 4dh or 4d-h."
      }
    },
    "required": [
      "filename",
      "data"
    ],
    "additionalProperties": false
  },
  "outputSchema": {
    "type": "object",
    "properties": {
      "bytesWritten": {
        "anyOf": [
          {
            "type": "number"
          },
          {
            "type": "string",
            "enum": [
              "NaN"
            ]
          },
          {
            "type": "string",
            "enum": [
              "Infinity"
            ]
          },
          {
            "type": "string",
            "enum": [
              "-Infinity"
            ]
          }
        ]
      },
      "offset": {
        "anyOf": [
          {
            "type": "number"
          },
          {
            "type": "string",
            "enum": [
              "NaN"
            ]
          },
          {
            "type": "string",
            "enum": [
              "Infinity"
            ]
          },
          {
            "type": "string",
            "enum": [
              "-Infinity"
            ]
          }
        ]
      },
      "size": {
        "anyOf": [
          {
            "type": "number"
          },
          {
            "type": "string",
            "enum": [
              "NaN"
            ]
          },
          {
            "type": "string",
            "enum": [
              "Infinity"
            ]
          },
          {
            "type": "string",
            "enum": [
              "-Infinity"
            ]
          }
        ]
      },
      "created": {
        "type": "boolean"
      }
    },
    "required": [
      "bytesWritten",
      "offset",
      "size",
      "created"
    ],
    "additionalProperties": false
  }
}),
sideEffect: "idempotent-write",
load: () => import("../write-hex"),

}),
deps: [ToolRegistry.node, LocationMutation.node, PermissionV2.node],
})
