import { describe, expect, test } from "bun:test"
import { Context, Option } from "effect"
import { HttpApi, HttpApiMiddleware, OpenApi } from "effect/unstable/httpapi"
import { makeDefaultApi } from "../src/api"
import { InvalidRequestError, SessionNotFoundError } from "../src/errors"

/**
 * The endpoint NAMESPACE of the one HTTP contract (todo.md ruling 11: *`packages/protocol`'s HttpApi
 * is the one contract, one generated artifact, one API version*).
 *
 * ## Where this came from
 *
 * Until 2026-07-29 the only mechanical cross-package contract check in the fast tier lived inside
 * `packages/client` — an unwired 10,826-line island (`httpapi-codegen` -> `client` -> `sdk-next`)
 * whose only importers were each other. It caught one real defect: `87bc97c3b`, where
 * `calendar.schedule.list` and `calendar.fires.list` collided. The island is deleted; the standing
 * decision is *"a guard that only exists inside otherwise-dead code is a guard with a hostage - just
 * make a good unit test instead"*, and this is that test.
 *
 * ## What is NOT ported, and why
 *
 * `httpapi-codegen` derived a client method name from the LAST dot-segment of the endpoint id, so
 * every endpoint in a group shared one flat namespace and `schedule.list` / `fires.list` both became
 * `list`. `packages/client/src/contract.ts` carried a 30-entry `endpointNames` map and a 3-entry
 * `omitEndpoints` set to work around exactly that rule.
 *
 * That rule died with its generator, and the claim is MEASURED rather than argued:
 *
 *   - the shipped client is `packages/sdk/js/src/v2/gen/sdk.gen.ts`, generated by `@hey-api` from
 *     `packages/sdk/openapi.json`, and it NESTS by dot-segment instead of flattening - today it
 *     carries `class Schedule { list() }` AND `class Fires { list() }` side by side, both reached as
 *     `calendar.schedule.list` / `calendar.fires.list`. The defect `87bc97c3b` fixed is not a defect
 *     of the shipped artifact.
 *   - all three `omitEndpoints` entries (`fs.read`, `pty.connect`, `pty.connectToken`) ARE in
 *     `openapi.json` and in the shipped SDK. That set recorded a limitation of the deleted emitter,
 *     not a property of the contract.
 *
 * So porting `endpointNames`/`omitEndpoints` would have pinned a naming rule that no artifact obeys,
 * and would have made this file green only because of a 30-entry map nothing consumes - the
 * guard-shaped no-op this repo has a ledger about. What IS carried over is the KNOWLEDGE: two
 * endpoints can silently collapse into one member of a generated client, and nothing else in the tree
 * checks it. The rule below is the live spelling of that same defect class.
 *
 * ## The live projection rule
 *
 * `effect/unstable/httpapi/OpenApi.ts:330-334` computes an operation id as the `OpenApi.Identifier`
 * annotation, falling back to `` `${group.identifier}.${endpoint.name}` `` when there is none. Every
 * endpoint in `packages/protocol` annotates one explicitly, as `v2.<endpoint id>` (104 of 104,
 * measured 2026-07-29), and that operation id is what the OpenAPI document publishes and what
 * `@hey-api` turns into the client's container/method tree. So the namespace properties that decide
 * whether two routes stay reachable are all properties of these ids.
 *
 * ## What no other test covers
 *
 * `packages/sdk/js/test/generated-drift.test.ts` is the neighbouring guard and it deliberately does
 * NOT cover this: it matches emitted `url: "..."` literals, and says so in as many words - *"Operation
 * ids are not usable for this: all 212 are rewritten into container/method names."* Two operations
 * that collapse into one client method still emit both URLs, so drift stays green while a route
 * silently loses its accessor. That is the hole this file fills.
 */

// Stub middleware, exactly as the deleted `packages/client/src/contract.ts` did: `makeDefaultApi`
// needs two `Context.Key`s and the namespace does not depend on which. Ids are namespaced under
// `@novaclaw/protocol/test/` because `context-key-uniqueness.test.ts` scans the whole tree for
// `HttpApiMiddleware.Service` registrations and fails on two implementations sharing one key.
class TestLocationMiddleware extends HttpApiMiddleware.Service<TestLocationMiddleware>()(
  "@novaclaw/protocol/test/LocationMiddleware",
) {}

class TestSessionLocationMiddleware extends HttpApiMiddleware.Service<TestSessionLocationMiddleware>()(
  "@novaclaw/protocol/test/SessionLocationMiddleware",
  { error: [InvalidRequestError, SessionNotFoundError] },
) {}

const Api = makeDefaultApi({
  locationMiddleware: TestLocationMiddleware,
  sessionLocationMiddleware: TestSessionLocationMiddleware,
})

type Route = {
  readonly group: string
  /** The `HttpApiEndpoint` id, e.g. `calendar.schedule.list`. */
  readonly name: string
  /** The EXPLICIT `OpenApi.Identifier` annotation, or undefined when the endpoint declares none. */
  readonly operationId: string | undefined
  readonly method: string
  readonly path: string
}

/** Every endpoint of an assembled HttpApi, flattened. */
function routesOf(api: typeof Api): Route[] {
  const out: Route[] = []
  HttpApi.reflect(api, {
    onGroup() {},
    onEndpoint({ endpoint, group, mergedAnnotations }) {
      out.push({
        group: group.identifier,
        name: endpoint.name,
        operationId: Option.getOrUndefined(Context.getOption(mergedAnnotations, OpenApi.Identifier)),
        method: endpoint.method,
        path: endpoint.path,
      })
    },
  })
  return out
}

const routes = routesOf(Api)

/** The prefix every operation id in this contract carries - "one API version" (ruling 11). */
const VERSION_PREFIX = "v2."

/** Keys that more than one route maps to, rendered as `key <- name, name`. */
function duplicateKeys(items: readonly Route[], key: (route: Route) => string): string[] {
  const seen = new Map<string, string[]>()
  for (const route of items) {
    const bucket = seen.get(key(route))
    if (bucket === undefined) seen.set(key(route), [route.name])
    else bucket.push(route.name)
  }
  return [...seen.entries()]
    .filter(([, names]) => names.length > 1)
    .map(([value, names]) => `${value} <- ${names.sort().join(", ")}`)
    .sort()
}

/**
 * An operation id that is a strict dot-PREFIX of another.
 *
 * The generated client nests by dot-segment, so `v2.calendar.schedule` alongside
 * `v2.calendar.schedule.list` asks the `Calendar` container to expose `schedule` as a method AND as
 * the getter for the `Schedule` sub-container. One of the two wins; nothing warns.
 */
function prefixOffenders(ids: readonly string[]): string[] {
  const unique = [...new Set(ids)]
  const out: string[] = []
  for (const id of unique) {
    const nested = unique.filter((other) => other.startsWith(`${id}.`)).sort()
    if (nested.length > 0) out.push(`${id} is also the container for ${nested.join(", ")}`)
  }
  return out.sort()
}

/**
 * A deliberately CONSERVATIVE model of what a code generator makes of one dot-segment: case-folded,
 * with every non-alphanumeric character dropped. Stricter than any single generator's rule on
 * purpose - ruling 11 says there is one contract and one generated artifact, but not which emitter
 * writes it, so the contract must survive a change of emitter. `list_all` and `listAll` are the same
 * member name to essentially all of them.
 */
const memberKey = (segment: string): string => segment.toLowerCase().replace(/[^a-z0-9]/g, "")

/**
 * Two SIBLING segments (same dot-parent) that collapse to one member name. This is the live spelling
 * of the defect `87bc97c3b` fixed: under the deleted emitter every endpoint in a group was a sibling,
 * so `schedule.list` and `fires.list` collided; under a nesting emitter only true siblings do.
 */
function siblingCollisions(ids: readonly string[]): string[] {
  // parent path -> normalized member name -> the distinct raw segments that produced it
  const tree = new Map<string, Map<string, Set<string>>>()
  for (const id of ids) {
    const parts = id.split(".")
    for (let index = 0; index < parts.length; index++) {
      const parent = parts.slice(0, index).join(".")
      const segment = parts[index]!
      let members = tree.get(parent)
      if (members === undefined) {
        members = new Map<string, Set<string>>()
        tree.set(parent, members)
      }
      let raw = members.get(memberKey(segment))
      if (raw === undefined) {
        raw = new Set<string>()
        members.set(memberKey(segment), raw)
      }
      raw.add(segment)
    }
  }
  const out: string[] = []
  for (const [parent, members] of tree)
    for (const [member, raw] of members)
      if (raw.size > 1) out.push(`${parent === "" ? "(root)" : parent}: ${[...raw].sort().join(" and ")} -> ${member}`)
  return out.sort()
}

describe("the sweep", () => {
  test("actually walked the assembled contract", () => {
    // Guards the guard: a broken reflect or a moved import empties `routes` and turns every
    // assertion below into a tautology. 104 endpoints across 21 groups on 2026-07-29, which is also
    // exactly the count of `v2.*` operations in the committed `packages/sdk/openapi.json`.
    expect(routes.length).toBeGreaterThanOrEqual(100)
    expect(new Set(routes.map((route) => route.group)).size).toBeGreaterThanOrEqual(20)
    expect(routes.map((route) => route.name)).toContain("calendar.schedule.list")
    expect(routes.map((route) => route.name)).toContain("calendar.fires.list")
  })
})

describe("the endpoint namespace", () => {
  test("every endpoint declares an explicit operation id, spelled v2.<endpoint id>", () => {
    // Two failures in one assertion because they are one fact. A MISSING annotation is not benign:
    // OpenApi falls back to `${group.identifier}.${endpoint.name}` - i.e. `server.calendar` +
    // `calendar.schedule.list` - which is unique but reshapes the shipped client's whole container
    // tree for that route. A MISMATCHED one lets the id namespace and the endpoint namespace drift,
    // after which the uniqueness checks below are each guarding only half the surface.
    const offenders = routes
      .filter((route) => route.operationId !== `${VERSION_PREFIX}${route.name}`)
      .map((route) => `${route.group}: ${route.name} -> ${route.operationId ?? "(no OpenApi.Identifier annotation)"}`)
      .sort()
    expect(
      offenders,
      [
        "An endpoint's OpenAPI operation id is not `v2.<endpoint id>`.",
        "That id is what packages/sdk/openapi.json publishes and what the generated client turns into",
        "its container/method tree, so it is the public name of the route. Add",
        '`.annotateMerge(OpenApi.annotations({ identifier: "v2.<endpoint id>", summary, description }))`.',
      ].join("\n"),
    ).toEqual([])
  })

  test("endpoint ids are unique across the whole contract", () => {
    expect(
      duplicateKeys(routes, (route) => route.name),
      "Two endpoints share an id, so they share an operation id and the second one overwrites the first.",
    ).toEqual([])
  })

  test("METHOD + path pairs are unique across the whole contract", () => {
    // Not a duplicate of the id check. `openapi.json` is keyed path -> method -> operation, so two
    // endpoints on one route+verb do not produce a conflict anywhere - one of them simply vanishes
    // from the document and from every client generated off it.
    expect(
      duplicateKeys(routes, (route) => `${route.method} ${route.path}`),
      "Two endpoints share a METHOD and path; one of them is unreachable and absent from the OpenAPI document.",
    ).toEqual([])
  })

  test("no operation id is a container for another", () => {
    expect(
      prefixOffenders(routes.map((route) => route.operationId ?? route.name)),
      [
        "An operation id is a strict dot-prefix of another one.",
        "The generated client nests by dot-segment, so the parent container would need the same name",
        "as both a method and a sub-container getter. Give the shorter route a leaf segment of its own",
        "(e.g. `calendar.schedule.get`, never bare `calendar.schedule`).",
      ].join("\n"),
    ).toEqual([])
  })

  test("sibling segments stay distinct once a generator normalizes them", () => {
    expect(
      siblingCollisions(routes.map((route) => route.operationId ?? route.name)),
      [
        "Two sibling segments of the operation-id tree collapse to one member name.",
        "This is the live form of the collision `87bc97c3b` fixed: the two routes become one accessor",
        "on the generated client and one of them is silently unreachable. Rename one segment.",
      ].join("\n"),
    ).toEqual([])
  })
})

describe("the guard bites (negative controls)", () => {
  // Each check above asserts an EMPTY list, which on its own cannot show that a non-empty one is
  // reachable. These drive the same pure functions with the defect injected.

  const route = (name: string, method: string, path: string): Route => ({
    group: "server.calendar",
    name,
    operationId: `${VERSION_PREFIX}${name}`,
    method,
    path,
  })

  test("a duplicate endpoint id is reported by name", () => {
    expect(
      duplicateKeys(
        [
          route("calendar.fires.list", "GET", "/api/calendar/fires"),
          route("calendar.fires.list", "GET", "/api/calendar/fires-2"),
        ],
        (item) => item.name,
      ),
    ).toEqual(["calendar.fires.list <- calendar.fires.list, calendar.fires.list"])
  })

  test("a duplicate METHOD + path is reported by name", () => {
    expect(
      duplicateKeys(
        [
          route("calendar.fires.list", "GET", "/api/calendar/fires"),
          route("calendar.fires.recent", "GET", "/api/calendar/fires"),
        ],
        (item) => `${item.method} ${item.path}`,
      ),
    ).toEqual(["GET /api/calendar/fires <- calendar.fires.list, calendar.fires.recent"])
  })

  test("an operation id that contains another is reported", () => {
    expect(prefixOffenders(["v2.calendar.schedule", "v2.calendar.schedule.list", "v2.calendar.fires.list"])).toEqual([
      "v2.calendar.schedule is also the container for v2.calendar.schedule.list",
    ])
    // ...and a name that merely shares a PREFIX STRING is not an offence. `v2.calendar.schedules`
    // starts with `v2.calendar.schedule`, but it is a sibling, not a child.
    expect(prefixOffenders(["v2.calendar.schedule.list", "v2.calendar.schedules.list"])).toEqual([])
  })

  test("two siblings that normalize to one member are reported", () => {
    expect(siblingCollisions(["v2.calendar.fires.listAll", "v2.calendar.fires.list_all"])).toEqual([
      "v2.calendar.fires: listAll and list_all -> listall",
    ])
    // A collision one level UP, where the leaf names are already distinct - the level the deleted
    // flat emitter could not see at all.
    expect(siblingCollisions(["v2.messenger.account.list", "v2.messenger.Account.create"])).toEqual([
      "v2.messenger: Account and account -> account",
    ])
  })

  test("the normalizer is what makes two spellings one member", () => {
    expect(memberKey("listAll")).toBe(memberKey("list_all"))
    expect(memberKey("projectCopy")).toBe(memberKey("project-copy"))
    expect(memberKey("schedule")).not.toBe(memberKey("schedules"))
  })

  test("schedule.list beside fires.list is NOT a collision, and that is the point", () => {
    // The literal defect of `87bc97c3b`, asserted to PASS. Under the deleted emitter both endpoints
    // flattened to `list` in one group; under the emitter we actually ship they are `Schedule.list`
    // and `Fires.list`, and both are in `packages/sdk/js/src/v2/gen/sdk.gen.ts` today. Pinned so
    // that nobody re-ports the dead flatten rule and calls a working contract broken.
    const live = ["v2.calendar.schedule.list", "v2.calendar.fires.list"]
    expect(siblingCollisions(live)).toEqual([])
    expect(prefixOffenders(live)).toEqual([])
    // The dead rule, for contrast: the last dot-segment of both is the same string.
    expect(live.map((id) => id.slice(id.lastIndexOf(".") + 1))).toEqual(["list", "list"])
  })
})
