import { describe, expect, test } from "bun:test"
import { ToolPolicy } from "@novaclaw/core/tool-policy"
import {
  describeValue,
  didRun,
  outcomeOf,
  patchedFields,
  providerRole,
  sortInterventions,
  summarize,
  toIntervention,
  toInterventions,
  type InstalledPolicy,
  type PolicyDecisionInfo,
} from "./session-policies"

/**
 * The presentation of a pre-action policy intervention, over every outcome the KERNEL can produce.
 *
 * 🔴 **The outcomes are generated by `ToolPolicy.compose`, not typed out here.** A fixture list
 * hand-copied from the kernel is a second copy of its vocabulary, and the day the kernel gains a
 * seventh outcome or renames one, a hand-written fixture keeps passing while the surface it stands
 * for starts lying. `OUTCOME_TYPES` and `compose` are imported so this file fails instead.
 *
 * ⚠️ Every hostile character below is written as an ESCAPE — typing the literal puts it in the
 * bundle and in every grep over the tree.
 */

const RLO = "\u202E" // right-to-left override — makes the trailing text render reversed
const ZWSP = "\u200B" // zero-width space — pads a string past a truncation boundary invisibly

/** The receipt row the gate would have written for a composed decision. Mirrors `record(…)`. */
const rowFor = (
  decision: ToolPolicy.Decision,
  over: Partial<PolicyDecisionInfo> = {},
): PolicyDecisionInfo => ({
  toolCallID: "call_1",
  tool: "bash",
  decision: decision.type,
  detail: decision.detail,
  providers: decision.providers,
  // The gate stores `null` for "nothing was patched" and the composer spells that absence as an
  // omitted field, so an empty patch must arrive as `undefined` here — not as `{}`.
  ...(Object.keys(decision.patch).length === 0 ? {} : { patched: decision.patch }),
  at: 1_700_000_000_000,
  ...over,
})

const answered = (id: string, outcome: ToolPolicy.Outcome): ToolPolicy.Result => ({
  id,
  kind: "answered",
  outcome,
  safetyCritical: true,
})

/** One provider's answer for each of the six, so `compose` produces each composed verdict in turn. */
const OUTCOME_FOR: Readonly<Record<ToolPolicy.OutcomeType, ToolPolicy.Outcome>> = {
  allow: { type: "allow" },
  context: { type: "context", text: "this ran with sudo" },
  patch: { type: "patch", fields: { command: "git --no-pager log" }, reason: "a pager would have wedged" },
  approve: { type: "approve", action: "irreversible_shell", resources: ["git push --force"], reason: "it can discard commits" },
  deny: { type: "deny", reason: "it deletes the filesystem root" },
  halt: { type: "halt", reason: "stop working" },
}

const installed: readonly InstalledPolicy[] = [
  { id: "git-no-pager", describe: "Rewrites paging git commands." },
  { id: "irreversible-shell", describe: "Refuses host-wide irreversible shell commands." },
]

describe("every outcome the kernel can produce reaches a readable row", () => {
  // Guards the guard: an OUTCOME_FOR that stopped covering the kernel's vocabulary would make the
  // loop below pass vacuously over whatever is left.
  test("the fixture covers the kernel's whole vocabulary", () => {
    expect(Object.keys(OUTCOME_FOR).toSorted()).toEqual([...ToolPolicy.OUTCOME_TYPES].toSorted())
  })

  for (const type of ToolPolicy.OUTCOME_TYPES) {
    test(`${type} — the composed decision survives into a view`, () => {
      const decision = ToolPolicy.compose([answered("git-no-pager", OUTCOME_FOR[type])])
      const view = toIntervention(rowFor(decision), installed)

      expect(view.outcome).toBe(type)
      expect(view.rawDecision).toBe(type)
      // Never invented: the sentence the panel shows is the sentence the model was given.
      expect(view.detail).toBe(decision.detail)
      // Prevented for exactly the two outcomes that prevent, and for no other.
      expect(view.ran).toBe(type === "deny" || type === "halt" ? false : true)
      expect(view.providers).toHaveLength(1)
      expect(view.providers[0]?.rawID).toBe("git-no-pager")
      expect(view.providers[0]?.installed).toBe(true)
      expect(view.providers[0]?.describe).toBe("Rewrites paging git commands.")
    })
  }

  test("allow is the ONE outcome that leaves nobody in `actedBy`", () => {
    const acted = ToolPolicy.OUTCOME_TYPES.filter((type) => {
      const decision = ToolPolicy.compose([answered("git-no-pager", OUTCOME_FOR[type])])
      return toIntervention(rowFor(decision), installed).actedBy.length > 0
    })
    expect(acted).toEqual(["context", "patch", "approve", "deny", "halt"])
  })

  test("patch — the REWRITTEN arguments are shown, field by field", () => {
    const decision = ToolPolicy.compose([answered("git-no-pager", OUTCOME_FOR.patch)])
    const view = toIntervention(rowFor(decision), installed)
    expect(view.patched).toEqual([{ field: "command", value: "git --no-pager log" }])
    // Everything else must NOT claim a rewrite happened.
    for (const other of ToolPolicy.OUTCOME_TYPES.filter((type) => type !== "patch")) {
      const composed = ToolPolicy.compose([answered("git-no-pager", OUTCOME_FOR[other])])
      expect(toIntervention(rowFor(composed), installed).patched).toEqual([])
    }
  })

  test("halt and deny both prevented the call, and the row still names WHICH", () => {
    for (const type of ["deny", "halt"] as const) {
      const decision = ToolPolicy.compose([answered("irreversible-shell", OUTCOME_FOR[type])])
      const view = toIntervention(rowFor(decision), installed)
      expect(view.ran).toBe(false)
      expect(view.actedBy).toEqual(["irreversible-shell"])
      expect(view.rawDecision).toBe(type)
    }
  })
})

describe("a receipt with several providers where only some intervened", () => {
  const decision = ToolPolicy.compose([
    answered("git-no-pager", OUTCOME_FOR.patch),
    answered("irreversible-shell", { type: "allow" }),
    answered("secrets-guard", { type: "context", text: "this folder holds credentials" }),
    { id: "slow-advisor", kind: "timed-out", safetyCritical: false },
  ])
  const view = toIntervention(rowFor(decision), [
    ...installed,
    { id: "secrets-guard", describe: "Notes when a folder holds credentials." },
    { id: "slow-advisor", describe: "An advisory policy." },
  ])

  test("the composed verdict is the strongest thing that happened", () => {
    expect(view.outcome).toBe("patch")
  })

  test("who ACTED, who was silent and who never answered are three separate lists", () => {
    expect(view.actedBy).toEqual(["git-no-pager", "secrets-guard"])
    // 🔴 The silent one is kept. A panel listing only the policy that acted cannot answer "was the
    // irreversible-shell guard even running?", which is the question a person asks afterwards.
    expect(view.silent).toEqual(["irreversible-shell"])
    // 🔴 And an unavailable provider is NOT filed as a refusal. It failed to answer; that its
    // silence was tolerated (advisory) or fatal (safety-critical) is a different fact.
    expect(view.unavailable).toEqual(["slow-advisor"])
  })

  test("the per-provider sentences survive, each attributed to its own policy", () => {
    const byID = new Map(view.providers.map((entry) => [entry.rawID, entry] as const))
    expect(byID.get("git-no-pager")?.detail).toContain("pager")
    expect(byID.get("secrets-guard")?.detail).toBe("this folder holds credentials")
    expect(byID.get("irreversible-shell")?.detail).toBe("")
    expect(byID.get("slow-advisor")?.outcome).toBe("timed-out")
  })

  test("summarize counts the row once, under the verdict, and flags the unavailable provider", () => {
    const summary = summarize([view])
    expect(summary).toEqual({
      total: 1,
      prevented: 0,
      rewritten: 1,
      approved: 0,
      annotated: 0,
      unnamed: 0,
      withUnresolved: 0,
      withUnavailable: 1,
    })
  })
})

describe("a policy id that no longer resolves", () => {
  const decision = ToolPolicy.compose([
    answered("retired-guard", OUTCOME_FOR.deny),
    answered("irreversible-shell", { type: "allow" }),
  ])

  test("is named as not installed HERE, not silently dropped from the list", () => {
    const view = toIntervention(rowFor(decision), installed)
    expect(view.unresolved).toEqual(["retired-guard"])
    // Still shown, and still credited with the refusal — a receipt that hid the policy responsible
    // would leave a user reading a refusal nobody performed.
    expect(view.actedBy).toEqual(["retired-guard"])
    expect(view.providers.map((entry) => entry.rawID)).toEqual(["irreversible-shell", "retired-guard"])
    expect(view.providers.find((entry) => entry.rawID === "retired-guard")?.describe).toBe("")
    expect(summarize([view]).withUnresolved).toBe(1)
  })

  test("🔴 'we could not read the installed list' is NOT the same claim as 'not installed'", () => {
    const view = toIntervention(rowFor(decision))
    for (const entry of view.providers) expect(entry.installed).toBeUndefined()
    // Nothing is accused of having vanished when we simply never asked.
    expect(view.unresolved).toEqual([])
    expect(summarize([view]).withUnresolved).toBe(0)
  })
})

describe("a decision word this build has never heard of", () => {
  const row: PolicyDecisionInfo = {
    toolCallID: "call_future",
    tool: "bash",
    decision: "quarantine",
    detail: "held in a quarantine this build knows nothing about",
    providers: [{ id: "future-guard", outcome: "quarantine" }],
    at: 1,
  }

  test("reads as unnamed rather than being folded into allow", () => {
    const view = toIntervention(row, installed)
    expect(view.outcome).toBe("unknown")
    // 🔴 The word is kept verbatim, so the surface can say WHAT it could not name.
    expect(view.rawDecision).toBe("quarantine")
    // 🔴 And "did it run" is a third answer. A boolean here would tell a reader the call went
    // through — the exact direction that turns a refusal into a reassuring sentence.
    expect(view.ran).toBeUndefined()
    expect(providerRole("quarantine")).toBe("unknown")
    expect(summarize([view]).unnamed).toBe(1)
  })

  test("the kernel's own six are all recognised — this arm only ever catches what is new", () => {
    for (const type of ToolPolicy.OUTCOME_TYPES) expect(outcomeOf(type)).toBe(type)
    expect(didRun("unknown")).toBeUndefined()
  })
})

describe("author text is treated as author text", () => {
  test("an id, a tool name and a rewritten value cannot lie about how they render", () => {
    const view = toIntervention({
      toolCallID: "call_x",
      tool: `bash${RLO}exe.`,
      decision: "patch",
      detail: `rewritten${ZWSP} for you`,
      providers: [{ id: `evil${RLO}yciloP`, outcome: "patch", detail: `why${ZWSP}` }],
      patched: { command: `rm -rf /${RLO}` },
      at: 1,
    })
    expect(view.tool).not.toContain(RLO)
    expect(view.detail).not.toContain(ZWSP)
    expect(view.providers[0]?.id).not.toContain(RLO)
    expect(view.providers[0]?.detail).not.toContain(ZWSP)
    // ⚠️ The rewritten VALUE too. It is the string that will actually run, so a bidi override in it
    // is the most consequential place for one.
    expect(view.patched[0]?.value).toBe("rm -rf /")
  })

  test("a policy or tool sanitized down to nothing still gets a label", () => {
    const view = toIntervention({
      toolCallID: "c",
      tool: ZWSP,
      decision: "deny",
      detail: "no",
      providers: [{ id: ZWSP, outcome: "deny" }],
      at: 1,
    })
    expect(view.tool).toBe("(unnamed tool)")
    expect(view.providers[0]?.id).toBe("(unnamed policy)")
    // The RAW id is untouched, so a match against the installed list still works.
    expect(view.providers[0]?.rawID).toBe(ZWSP)
  })
})

describe("values, ordering and the empty case", () => {
  test("a non-string replacement is shown as JSON rather than as [object Object]", () => {
    expect(describeValue({ a: 1 })).toBe('{"a":1}')
    expect(describeValue(["x", "y"])).toBe('["x","y"]')
    expect(describeValue(7)).toBe("7")
    expect(describeValue(null)).toBe("null")
    // A cycle cannot be stringified, and a policy is not trusted to have avoided one.
    const cyclic: Record<string, unknown> = {}
    cyclic["self"] = cyclic
    expect(describeValue(cyclic)).toBe("[object Object]")
  })

  test("replaced fields are sorted by name, not left in wire order", () => {
    expect(patchedFields({ zeta: "1", alpha: "2" }).map((entry) => entry.field)).toEqual(["alpha", "zeta"])
    expect(patchedFields(undefined)).toEqual([])
  })

  test("interventions are newest first, with a total order so re-fetching cannot reshuffle them", () => {
    const at = (key: string, when: number): PolicyDecisionInfo => ({
      toolCallID: key,
      tool: "bash",
      decision: "deny",
      detail: "no",
      providers: [],
      at: when,
    })
    expect(toInterventions([at("a", 1), at("c", 3), at("b", 2)]).map((v) => v.toolCallID)).toEqual(["c", "b", "a"])
    // Same millisecond: the key breaks the tie, so the order is stable across reads.
    const tied = sortInterventions(toInterventions([at("b", 5), at("a", 5)]))
    expect(tied.map((v) => v.toolCallID)).toEqual(["a", "b"])
  })

  test("🔴 an empty list is a POSITIVE statement, and summarize reports it as one", () => {
    expect(summarize([])).toEqual({
      total: 0,
      prevented: 0,
      rewritten: 0,
      approved: 0,
      annotated: 0,
      unnamed: 0,
      withUnresolved: 0,
      withUnavailable: 0,
    })
  })

  test("an `allow` ROW is never 'nothing happened' — the gate writes one only when a policy went silent", () => {
    const decision = ToolPolicy.compose([
      answered("irreversible-shell", { type: "allow" }),
      { id: "slow-advisor", kind: "errored", safetyCritical: false },
    ])
    expect(decision.type).toBe("allow")
    const view = toIntervention(rowFor(decision), installed)
    expect(view.ran).toBe(true)
    expect(view.unavailable).toEqual(["slow-advisor"])
    // Counted as an annotation rather than discarded: the call ran and not every policy answered.
    expect(summarize([view])).toMatchObject({ total: 1, annotated: 1, withUnavailable: 1 })
  })
})
