import { closeSync, existsSync, openSync, readdirSync, readSync, statSync, type Dirent } from "node:fs"
import path from "node:path"

import type { Channel } from "./utils"

/**
 * What `extraResources` stages beside the app, and what an ABSENCE means for each entry.
 *
 * 🔴 **A packaging step that "verifies" by not throwing verifies nothing.** An `extraResources`
 * `from:` pointing at a missing or empty directory is not an electron-builder error: it copies
 * nothing and the pack succeeds. Every native tree we ship fails SILENTLY when it is absent — a
 * missing DHT looks like a network with nobody on it, a missing host library turns file watching off
 * without an error because an unavailable host means the layer provides no binding at all, a missing
 * watchdog is invisible until something crashes. This repo has shipped that class twice: a stale
 * renderer out of a Vite cache, and a native build degraded by a soft catch. Both times every step
 * reported success.
 *
 * ⚠️ **This is a LEDGER rather than a list of checks, and the difference is the point.** The DHT and
 * the watchdog each acquired a guard when somebody remembered to write one; `host/` never did, and
 * neither would the next entry. Here the config's OWN entries are the keys: an `extraResources`
 * entry with no policy is a build failure that names itself, so a resource cannot be added to the
 * package without a decision about whether its absence is acceptable. That is the only form of this
 * check that does not go stale the moment the config grows.
 */
export type StagingRequirement =
  /** Its absence is a broken build on every channel. */
  | "required"
  /** Tolerated on the non-publishable development channel only — the DHT's existing exemption. */
  | "release-only"
  /** Legitimately absent on some machines; reported, never fatal. */
  | "optional"

export type StagedResource = { readonly from: string; readonly to: string }

type Policy = {
  readonly requirement: StagingRequirement
  /**
   * A named file that must exist inside the staged directory, when we know one. A directory holding
   * *something* is a weaker claim than a directory holding the artifact this platform needs, and the
   * gap between the two is exactly where a wrong-platform or half-written staging tree lives.
   */
  readonly binary?: (platform: NodeJS.Platform) => string | undefined
}

/** The library `packages/host/build.ts` emits for a platform, and nothing on macOS — it compiles the
 *  Linux backend there, which cannot build, and `prebuild.ts` tolerates exactly that. */
export function hostLibraryName(platform: NodeJS.Platform): string | undefined {
  if (platform === "win32") return "host.dll"
  if (platform === "darwin") return undefined
  // `host.so`, not `libhost.so`: `host.bun.ts` resolves `host.${suffix}` from `bun:ffi`.
  return "host.so"
}

const POLICIES: Readonly<Record<string, Policy>> = {
  // Generated by `scripts/copy-icons.ts` and gitignored, so a direct electron-builder invocation on a
  // fresh clone stages nothing here and the window silently falls back to the Electron default icon.
  "icons/": { requirement: "required" },
  "host/": {
    // 🔴 Required on EVERY channel, not release-only, because that is the owner's standing ruling
    // (2026-08-19) and `prebuild.ts` already refuses a Windows build whose host module did not
    // compile. macOS drops out through `hostLibraryName` returning nothing: there is no backend to
    // require there. The 0.1.63 release packaged a week-old library because a soft catch shrugged
    // and the word WARNING scrolled past in a 4,000-line log — a warning is not a gate.
    requirement: "required",
    binary: hostLibraryName,
  },
  // `verifyStagedDht` additionally probes the executable and its manifest; this covers the same entry
  // from the ledger's side so the two can never disagree about whether it was checked at all.
  "dht/": { requirement: "release-only" },
  // Most machines have no cargo toolchain and `prebuild.ts` warns rather than failing. What is lost
  // is the outermost supervision layer, not the product.
  "watchdog/": {
    requirement: "optional",
    binary: (platform) => (platform === "win32" ? "novaclaw-watchdog.exe" : "novaclaw-watchdog"),
  },
  // Downloaded and SHA-256 verified by their `prepare-*.ts` provisioners before every Windows build,
  // and gitignored. An agent that believes it can search, compile or edit images and cannot is a
  // capability that exists on disk and not in the product.
  "third-party/ripgrep/": { requirement: "required" },
  "third-party/w64devkit/": { requirement: "required" },
  "third-party/imagemagick/": { requirement: "required" },
}

/** The platform's object-file magic, so a Linux `.so` staged into a Windows pack is caught here
 *  rather than at the user's first launch. */
const MAGIC: Partial<Record<NodeJS.Platform, { readonly bytes: readonly number[]; readonly name: string }>> = {
  win32: { bytes: [0x4d, 0x5a], name: "a Windows PE image" },
  linux: { bytes: [0x7f, 0x45, 0x4c, 0x46], name: "an ELF image" },
}

function isRequired(policy: Policy, channel: Channel): boolean {
  if (policy.requirement === "required") return true
  if (policy.requirement === "optional") return false
  return channel !== "dev"
}

/** The first non-empty regular file at or under `directory`, or undefined. Short-circuits on the
 *  first hit, so proving the 594 MB w64devkit tree is not empty costs one `readdir`. */
function firstFile(directory: string, depth = 3): string | undefined {
  let entries: Dirent<string>[]
  try {
    entries = readdirSync(directory, { withFileTypes: true, encoding: "utf8" })
  } catch {
    return undefined
  }
  for (const entry of entries) {
    const full = path.join(directory, entry.name)
    if (entry.isFile()) {
      try {
        if (statSync(full).size > 0) return full
      } catch {
        /* vanished between readdir and stat — not a file we can count on */
      }
      continue
    }
    if (entry.isDirectory() && depth > 0) {
      const found = firstFile(full, depth - 1)
      if (found) return found
    }
  }
  return undefined
}

function assertNativeBinary(file: string, platform: NodeJS.Platform, label: string) {
  const size = statSync(file).size
  if (size === 0) throw new Error(`${label}: ${file} is present but EMPTY — a zero-byte artifact is not a build`)
  const magic = MAGIC[platform]
  if (!magic) return
  const head = Buffer.alloc(magic.bytes.length)
  const handle = openSync(file, "r")
  try {
    readSync(handle, head, 0, head.length, 0)
  } finally {
    closeSync(handle)
  }
  for (const [index, byte] of magic.bytes.entries())
    if (head[index] !== byte)
      throw new Error(
        `${label}: ${file} is not ${magic.name} — this build targets ${platform}, so the staged artifact ` +
          `was built for something else (or is a placeholder). Rebuild it on this platform.`,
      )
}

export type StagedResourceVerdict = { readonly to: string; readonly verdict: "verified" | "absent" | "not-applicable" }

/**
 * Verify one side of the staging — the source tree before the copy, or the packaged tree after it.
 *
 * `resolve` maps an entry to the directory to inspect, which is what lets the SAME ledger drive both
 * halves. A check that only ran before the copy would still miss a copy that silently failed, and
 * one that only ran after it would let a release get as far as a distributable before saying so.
 */
export function verifyStagedResources(input: {
  readonly resources: readonly StagedResource[]
  readonly channel: Channel
  readonly resolve: (entry: StagedResource) => string
  readonly platform?: NodeJS.Platform
  readonly label: string
  readonly warn?: (message: string) => void
}): readonly StagedResourceVerdict[] {
  const platform = input.platform ?? process.platform
  const warn = input.warn ?? ((message: string) => console.warn(message))
  return input.resources.map((entry): StagedResourceVerdict => {
    const policy = POLICIES[entry.to]
    // 🔴 The ledger is keyed on the CONFIG's own entries, so this is the arm that keeps it honest:
    // a new staged resource cannot reach a user until somebody has said what its absence means.
    if (!policy)
      throw new Error(
        `${input.label}: nothing says whether "${entry.to}" may be missing. Every extraResources entry ` +
          `needs a policy in scripts/staged-resources.ts — an unclassified native tree is exactly how ` +
          `a resource ships absent with the build log green.`,
      )

    const directory = input.resolve(entry)
    const required = isRequired(policy, input.channel)
    const binary = policy.binary?.(platform)
    // A platform with no artifact of its own (the host library on macOS) is not a degradation.
    if (policy.binary && !binary) return { to: entry.to, verdict: "not-applicable" }

    if (!existsSync(directory)) {
      if (required) throw new Error(`${input.label}: "${entry.to}" is REQUIRED and ${directory} does not exist`)
      warn(`DEVELOPMENT ONLY: packaging without "${entry.to}" (${directory} does not exist).`)
      return { to: entry.to, verdict: "absent" }
    }

    if (binary) {
      const file = path.join(directory, binary)
      if (!existsSync(file)) {
        if (required)
          throw new Error(`${input.label}: "${entry.to}" is REQUIRED and ${file} is missing from ${directory}`)
        warn(`DEVELOPMENT ONLY: packaging without "${entry.to}" (${file} is missing).`)
        return { to: entry.to, verdict: "absent" }
      }
      assertNativeBinary(file, platform, input.label)
      return { to: entry.to, verdict: "verified" }
    }

    if (!firstFile(directory)) {
      // ⚠️ An EMPTY directory, not a missing one. This is the shape that made the check worth
      // writing: `extraResources` copies an empty tree without complaint, so the entry looks honoured
      // in the build log and the product ships with nothing there.
      if (required)
        throw new Error(`${input.label}: "${entry.to}" is REQUIRED and ${directory} holds no non-empty file`)
      warn(`DEVELOPMENT ONLY: packaging without "${entry.to}" (${directory} is empty).`)
      return { to: entry.to, verdict: "absent" }
    }
    return { to: entry.to, verdict: "verified" }
  })
}

/** Where `extraResources` land inside a packed application tree. */
export function packagedResourcesDirectory(appOutDir: string, platform: NodeJS.Platform): string {
  if (platform !== "darwin") return path.join(appOutDir, "resources")
  const bundle = readdirSync(appOutDir).find((entry) => entry.toLowerCase().endsWith(".app"))
  if (!bundle) throw new Error(`packaged application: no .app bundle in ${appOutDir}`)
  return path.join(appOutDir, bundle, "Contents", "Resources")
}
