#!/usr/bin/env bun
// Regenerate schema-only registrations from the same metadata and dependency declarations that
// the implementation uses. Run with --check in verification; never hand-edit deferred/*.gen.ts.
import fs from "node:fs/promises"
import path from "node:path"
import ts from "typescript"
import { Effect } from "effect"
import { Tool } from "../src/tool/tool"

const root = path.resolve(import.meta.dir, "../src/tool")
const check = process.argv.includes("--check")
const generated = path.join(root, "deferred")
if (!check) await fs.mkdir(generated, { recursive: true })
const candidates = (await fs.readdir(root)).filter((name) => name.endsWith(".ts"))
let count = 0
const pending: string[] = []
const outputs = new Set<string>()
for (const file of candidates) {
  const source = await fs.readFile(path.join(root, file), "utf8")
  if (!source.includes("Tool.withDeferred(")) continue
  const parsed = ts.createSourceFile(file, source, ts.ScriptTarget.Latest, true)
  const declarations = parsed.statements.flatMap((s) =>
    ts.isVariableStatement(s) ? [...s.declarationList.declarations] : [],
  )
  const node = declarations.find((d) => ts.isIdentifier(d.name) && d.name.text === "node")?.initializer
  if (!node || !ts.isCallExpression(node) || !ts.isObjectLiteralExpression(node.arguments[0]!))
    throw new Error(`No node: ${file}`)
  const config = node.arguments[0] as ts.ObjectLiteralExpression
  const deps = config.properties.find((p) => p.name?.getText(parsed) === "deps")
  if (!deps || !ts.isPropertyAssignment(deps)) throw new Error(`No dependencies: ${file}`)
  const references = new Set<string>()
  const walk = (n: ts.Node) => {
    if (ts.isIdentifier(n) && !(ts.isPropertyAccessExpression(n.parent) && n.parent.name === n)) references.add(n.text)
    ts.forEachChild(n, walk)
  }
  walk(deps.initializer)
  const imports: string[] = []
  const imported = new Set<string>()
  for (const s of parsed.statements) {
    if (
      !ts.isImportDeclaration(s) ||
      !s.importClause?.namedBindings ||
      !ts.isNamedImports(s.importClause.namedBindings)
    )
      continue
    const kept = s.importClause.namedBindings.elements.filter((e) => references.has(e.name.text))
    if (!kept.length) continue
    for (const e of kept) imported.add(e.name.text)
    const spec = (s.moduleSpecifier as ts.StringLiteral).text
    imports.push(
      `import { ${kept.map((e) => e.getText(parsed)).join(", ")} } from ${JSON.stringify(spec.startsWith(".") ? "../" + spec : spec)}`,
    )
  }
  for (const name of references) if (!imported.has(name)) throw new Error(`Unresolved dependency ${name} in ${file}`)
  const module = await import(path.join(root, file))
  if (!module.metadata) throw new Error(`Extract schema metadata first: ${file}`)
  if (module.metadata.variants || module.metadata.outputPreview || source.includes("Tool.withPermission("))
    throw new Error(`Extend lazy metadata before adding variants, preview policy or permission remapping: ${file}`)
  const descriptor = Tool.make({ ...module.metadata, execute: () => Effect.die("metadata only") })
  const definition = Tool.definition(module.name, descriptor)
  let available = ""
  if (module.available) {
    const declaration = parsed.statements.find(
      (s) =>
        ts.isExportDeclaration(s) &&
        s.exportClause &&
        ts.isNamedExports(s.exportClause) &&
        s.exportClause.elements.some((e) => e.name.text === "available"),
    ) as ts.ExportDeclaration | undefined
    if (!declaration?.moduleSpecifier || !declaration.exportClause || !ts.isNamedExports(declaration.exportClause))
      throw new Error(`Availability needs a lightweight re-export: ${file}`)
    const binding = declaration.exportClause.elements.find((e) => e.name.text === "available")!
    imports.push(
      `import { ${binding.getText(parsed)} } from ${JSON.stringify("../" + (declaration.moduleSpecifier as ts.StringLiteral).text)}`,
    )
    available = "available,"
  } else if (source.includes("ToolRegistry.withAvailability(")) throw new Error(`Missing lazy availability: ${file}`)
  const stem = file.slice(0, -3)
  const text = `// Generated by packages/core/script/deferred-builtins.ts. Do not edit.\nimport { ToolDefinition } from "@novaclaw/llm"\nimport { makeLocationNode } from "../../effect/app-node"\nimport { LazyBuiltin } from "../lazy-builtin"\n${imports.join("\n")}\n\nexport const node = makeLocationNode({\nname: ${JSON.stringify(module.node.name)},\nlayer: LazyBuiltin.layer({\ndefinition: new ToolDefinition(${JSON.stringify(definition, null, 2)}),\nsideEffect: ${JSON.stringify(Tool.sideEffect(descriptor))},\nload: () => import("../${stem}"),\n${available}\n}),\ndeps: ${deps.initializer.getText(parsed)},\n})\n`
  const output = path.join(generated, `${stem}.gen.ts`)
  outputs.add(`${stem}.gen.ts`)
  if (check) {
    if ((await fs.readFile(output, "utf8").catch(() => "")) !== text) pending.push(stem)
  } else await fs.writeFile(output, text)
  count++
}
for (const file of await fs.readdir(generated)) {
  if (file.endsWith(".gen.ts") && !outputs.has(file)) {
    if (check) pending.push(`obsolete:${file}`)
    else await fs.unlink(path.join(generated, file))
  }
}
if (pending.length) throw new Error(`Deferred registrations need regeneration: ${pending.join(", ")}`)
console.log(`${count} deferred built-in registrations ${check ? "verified" : "generated"}`)
